core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java

This overrides a few more methods in CountingOutputStream to improve performance
by avoiding FilterOutputStream's terrible behavior of converting all write calls
into underlying.write(int) streams, i.e. it writes everything one byte at a
time.
This makes a pretty significant improvement to throughput tests for kafka-rest. @nehanarkhede might make sense for you to review, I think you're the only other one who has looked at this code before.

Improve performance of CountingOutputStream.

---

core/pom.xml
core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java

Hi guys,
Have added new conf parameter to have ability to use Jetty's org.eclipse.jetty.servlets.CrossOriginFilter filter. 
The filter enables Cross-origin resource sharing (https://en.wikipedia.org/wiki/Cross-origin_resource_sharing), which is very convenient if I want to use kafka-rest api directly from client browser's javascript code. 
Please review.

added new config parameter to enable Cross-origin resource sharing

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java

by default CrossOriginFilter will only allow cors for GET/POST/HEAD. 
we will now allow users to config a comma separated list of VERBs via `access.control.allowed.methods`

allow cors on any HTTP verb available.

---

core/src/main/java/io/confluent/rest/Application.java
core/src/test/java/io/confluent/rest/ApplicationTest.java

This change is to support https://github.com/confluentinc/schema-registry/pull/371

Generalizing Application.parseListeners() to be used by the Schema Registry

---

core/pom.xml
core/src/main/java/io/confluent/rest/Application.java

Fixes for #46.  I enabled the jetty JMX metrics per: http://www.eclipse.org/jetty/documentation/current/jmx-chapter.html

Issue #46: Expose Jetty JMX metrics

---

core/src/main/java/io/confluent/rest/Application.java

Was running into an issue where an `ExceptionMapper` instance I'd registered for all `Throwable`s was getting overridden by the `GenericExceptionMapper` class that's registered in the `configureBaseApplication()` method. At the moment it's not preferable to just avoid calling `super.configureBaseApplication()` altogether, since I still want to register a body provider for JSON handling (current workaround is to not call `super.configureBaseApplication()` and just copy+paste the JSON body provider code into the subclass's `configureBaseApplication()` method). So, it'd be nice if there were a separate method for registering the body provider without also registering the `GenericExceptionMapper` instance or, for that matter, any unwanted `ExceptionMapper`s.

Decompose adding JSON provider into separate, protected method

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/ApplicationTest.java

This PR adds the ability to configure paths that can be accessed unauthenticated while turning on authentication. We add unauthenticated constraint for each of the path if there is an existing constraint. This is useful when people want to provide open access for all GET requests or health check resources, etc.

Ability to skip authentication for specific paths

---

Jenkinsfile
pom.xml

Updating upstream dependency to common
- Based on ST-620. common-docker is being consolidated to common
- Staged PR for https://github.com/confluentinc/common/pull/91

Updating upstream dependency to common

---

core/pom.xml
core/src/main/java/io/confluent/rest/Application.java
core/src/test/java/io/confluent/rest/SaslTest.java
pom.xml

Fixes: [MMA-2878](https://confluentinc.atlassian.net/browse/MMA-2878)
Noticed that the rest utils does not currently set up security on the websocket end points. This PR adds a puts the same auth on the websocket requests as was already on the http requests, and adds suitable tests.

MMA-2878 - Enable security on websocket end points as well as http.

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/CustomInitTest.java

This PR looks to add some very basic hooks to allow the RESTful and WS servlets to be customised using _configuration_, rather than by subclassing.
It's petty basic. To customise, you write a class that `implements BiConsumer<ServletContextHandler, ? extends RestConfig>` and add it to the list of initialisers for either or both servlets. The app will then instantiate your class and pass you the appropriate servlet and app config, (after all other initialisation has been done, but before it is started), for you to do what you want with.
I've used `BiConsumer` as its a standard Java interface, meaning no need for any other deps.
There is obviously a risk that people can do dumb stuff with this, but that's not really the point. People can always do dumb stuff!  This enabled people to tweak …

Support custom init.

---

core/src/main/java/io/confluent/rest/Application.java

* WADL exposes available method names on Jersey classes, which can be a
security concern
* This feature also does not currently work with Java > 8 since we don't
provide a JAXB runtime implementation.

disable Jersey generating WADL for OPTIONS request

---

core/src/main/java/io/confluent/rest/Application.java
core/src/test/java/io/confluent/rest/ApplicationTest.java

* disable authentication for OPTIONS requests when CORS is enabled
* do not forward CORS preflight requests down the filter chain
Note: regular OPTIONS requests without CORS preflight headers will still
be forwarded down the filter chain, so this would break applications
that require authentication for those requests. I don't think we have
any application explicitly handling OPTIONS requests, so the risk should
be low.

fix authentication breaking CORS preflight requests

---

core/src/main/java/io/confluent/rest/Application.java

Allow applications built on `rest.Application` to extract the `SslContextFactory`.
Refactor creation of `SslContextFactory` so that it gets created and configured once instead of potentially multiple times.

Expose SslContextFactory

---

core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java

Include percentile metrics for latency.
Open Question: I just picked an arbitrary bucket size and sizing scheme. If anyone can recommend a scientific way to get that, it's great.

Add percentile metrics for latency

---

core/src/main/java/io/confluent/rest/auth/AuthUtil.java
core/src/test/java/io/confluent/rest/auth/AuthUtilTest.java

adding two methods:
- `AuthUtil.createSecuredConstraint(config, path)`
- `AuthUtil.createUnsecuredConstraint(config, path)`
& generalizing some `Constraint` creation code
these methods would be useful for adding custom auth constraints

adding helper methods to AuthUtil for creating constraints

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java

This is part of our effort to enable anonymous access for Schema Registry.
The changes here add a configuration, `ssl.client.auth.requested`, which corresponds to a boolean value that's passed to the `setWantClientAuth(...)` method of the underlying `SslContextFactory` if and only if the `ssl.client.auth` configuration is not set to `true`. If both `ssl.client.auth` and `ssl.client.auth.requested` are set to `true`, the `ssl.client.auth` configuration is given precedence and a warning message is logged.

CC-3633: Enable SSL client authentication to be requested but not required

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java

In newer [version](https://github.com/confluentinc/rest-utils/pull/142) of Jetty,  default value for ssl.endpoint.identification.algorithm was changed to https. This PR sets default value for ssl.endpoint.identification.algorithm to https. Also allow users to set empty string to restore the previous behaviour.

Set default value for ssl.endpoint.identification.algorithm to https

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java

Jetty recently enabled hostname verification by default, but this
only makes sense for clients. They introduced a new subclass that
should be used in server contexts.

CC-5576: Use SslContextFactory.Server to disable server-side hostname verification

---

checkstyle/suppressions.xml
core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java
pom.xml

This will allow us to distinguish between server errors and
user/input errors, which will let us specify alerting better.
Specifically, for projects like Schema Registry we may want to alert only on 5xx errors and not 4xx errors.

Include separate metrics for each HTTP error code

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/ApplicationServer.java

Broke KSQL (again): https://jenkins.confluent.io/job/confluentinc/job/ksql/job/5.4.x/88/

Remove @Deprecated from Application and ApplicationServer methods.

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/ApplicationGroup.java
core/src/main/java/io/confluent/rest/ApplicationServer.java

See https://github.com/confluentinc/ce-kafka/pull/973.

Detaches the MetadataServer life-cycle from RBAC provider.

---

core/src/main/java/io/confluent/rest/ApplicationServer.java

This is to ensure that handlers are ready for incoming requests.
Without this fix, Schema Registry would return 404 because handlers had not yet been initialized.  This caused tests in `sr_master_failover_test.py` to fail, since in the tests 404 should only be returned if a subject or version no longer exists.

Call super.doStart last

---

pom.xml

The Jetty version got recently bumped from 9.4.20.v20190813 to 9.4.26.v20200117 (https://github.com/confluentinc/rest-utils/commit/cfd2c46cdde5e53df751a1f71073bead474d0e06).
After the bump most rest-proxy tests started outputting stack-traces of the form:
```
ERROR Request Failed with exception  (io.confluent.rest.exceptions.DebuggableExceptionMapper:62)
java.lang.NoSuchMethodError: org.eclipse.jetty.server.Response.closeOutput()V
at org.glassfish.jersey.jetty.JettyHttpContainer$ResponseWriter.commit(JettyHttpContainer.java:326)
at org.glassfish.jersey.jetty.JettyHttpContainer$ResponseWriter.failure(JettyHttpContainer.java:359)
at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:436)
at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRunti …
```

Downgrade Jetty version to 9.4.24.v20191120 to "fix" rest-proxy tests.

---

core/src/main/java/io/confluent/rest/exceptions/KafkaExceptionMapper.java

Simple PR to better handle the `InvalidFormatException` which gets thrown if you try to commit offsets with a String rather than a Long with Rest Proxy.  This is for https://github.com/confluentinc/kafka-rest/issues/501 and now returns the 400 error code and suppresses the long stack trace being output into the log.

Catch invalid format exception: #501

---

core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/SslTest.java

`ssl.client.auth` is a String in Kafka that accepts lower-case values `required/requested/none`. In REST utils, we have two configs, a boolean `ssl.client.auth=true/false` that is deprecated and another config `ssl.client.authentication` that takes upper-case values `REQUIRED/REQUESTED/NONE`. `ssl.client.authentication`  has higher precedence than `ssl.client.auth`.
To make REST utils consistent with Kafka without breaking existing configuration, this PR:
1) Undeprecates `ssl.client.auth` and deprecates `ssl.client.authentication`
2) Makes both configs case insenstive
3) Makes `ssl.client.auth` a String config that accepts `true/false/required/requested/none`
4) Retains the existing precedence where`ssl.client.authentication` overrides `ssl.client.auth`
This PR was originally written …

CPKAFKA-4948: Make ssl.client.auth for REST consistent with Kafka

---

core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/TestCustomizeThreadPool.java

This is new PR for customizing the thread pool and size of request queue. This PR is from old PR https://github.com/confluentinc/rest-utils/pull/150. It is too much work for merging the PR 150 due to code had dramatic changes since supporting one Jetty Server instance can contain multiple Applications. Milo had reviewed old PR and team decided to merge code after 5.4. Please see old review comments in old PR.

SEC-592:  Customize Jetty request queue and threadpool size

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/MetricsListener.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/test/java/io/confluent/rest/SaslTest.java
core/src/test/java/io/confluent/rest/SslTest.java
core/src/test/java/io/confluent/rest/TestMetricsReporter.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

Jira: https://confluentinc.atlassian.net/browse/MMA-7195
As part of our efforts to converge on a single telemetry pipelines for Cloud, Hosted Monitoring, and Proactive Support, we want to standardize on one metrics library and associated metrics collection framework.
This change is prerequisite for Telemetry Reporter work.
Verfication
baseline: https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/3721/console
with this change: https://jenkins.confluent.io/job/system-test-confluent-platform-branch-builder/3715/

Migrate rest-utils to use AK library instead of common-metrics

---

core/src/main/java/io/confluent/rest/Application.java

**Why**
Allows the currently configured metrics object to be reused

Add getter for Application's Metrics object

---

pom.xml

MINOR: Upgrade jetty to 9.4.30.v20200611 and jersey to 2.31

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/ApplicationGroup.java
core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/test/java/io/confluent/rest/ApplicationTest.java
core/src/test/java/io/confluent/rest/metrics/RequestScopedMetricsIntegrationTest.java

We leak some metrics reporter configs into kafka-rest. This is intended facilitate breaking some of that coupling.

Extensible Application Metrics instance configuration

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/TestMetricsReporter.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

What: Helper function to capture all metric reporter specific configs
Why: Currently rest-utils passes all originals to the metrics reporter. This may prove problematic for some reporters and or higher order applications with stricter configuration handling needs.

Use prefix to propagate metrics reporter configs

---

core/pom.xml
examples/pom.xml

- Confluent repackaged version fixes CVE-2019-17571
- `common/pom.xml` excludes default log4j as a transitive dependency, and the repackaged version must be explicitly added.
Ref: https://github.com/confluentinc/common/pull/270

SEC-1034: log4j migration to confluent repackaged version

---

core/src/main/java/io/confluent/rest/auth/AuthUtil.java
core/src/test/java/io/confluent/rest/SslTest.java
core/src/test/java/io/confluent/rest/auth/AuthUtilTest.java

This had to be done for https://confluentinc.atlassian.net/browse/ESCALATION-3168.
When Customer has RBAC/CORS enabled together, anonymous requests run into issue because of jetty/OAuthBearerAuthenticator.
We came to conclusion to get it fixed in rest-utils.
This change will require all HTTP methods (including OPTION) to require authentication if it was enabled.

Removed OPTION omission for CORS

---

core/src/test/java/io/confluent/rest/ApiHeadersTest.java
core/src/test/java/io/confluent/rest/SslTest.java

What
---
Fix build failure: https://jenkins.confluent.io/view/Packaging%20Snapshot/job/confluentinc/job/packaging/job/master/1823/execution/node/302/log/
Why
---
Jenkins build failed because TestSslUtils.CertificateBuilder api changed in kafka-clients-6.1.0-ccs-20200721.175538-46-test.jar

Fix build failure

---

pom.xml

different versions across the stack are causing incompatibilities

inherit guava version from common pom

---

core/pom.xml
examples/pom.xml

This pull request cherry-picks a commit from `master` to add explicit `io.confluent:confluent-log4j` dependency, because we blacklist the (vulnerable) tranistive dependency `log4j:log4j` of `org.slf4j:slf4j-log4j12` explicitly in `common`. `io.confluent:confluent-log4j` is a drop-in replacement of `log4j:log4j` with a fix for the vulnerability.

SEC-1307: Backport "log4j replacement with confluent repackaged version"

---

core/src/test/java/io/confluent/rest/ApiHeadersTest.java
core/src/test/java/io/confluent/rest/SslTest.java

https://github.com/confluentinc/kafka/commit/7be8bd8cbfea5cc19f815a142c4689e97728ea4b#diff-10d99f28c40b6cd9640f95b1c763a7b2b4daaa0209249e1a724698f28a90df9bL118-L126 Removed the function definition of `createKeyStore` that tests in this repo were using. This PR fixes the compilation errors by conforming to the remaining definition of `createKeyStore` that required two Password args.
I was able to compile and run the tests locally

MINOR: Fix compilation error from createKeyStore

---

Jenkinsfile
core/pom.xml
examples/pom.xml
package/pom.xml
pom.xml
test/pom.xml

Setting the jenkins config to use nano versioning. No longer need to define upstream repos as we now define downstream repos which will be automated in the future. Removed all of the snapshot versions and replaced with nano versions. Updated all of the dependency versions.
These changes will be merged during phase two of the nano versioning roll out.

ST-3461: Nano versioning

---

core/pom.xml
core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/FileWatcher.java
core/src/test/java/io/confluent/rest/ApiHeadersTest.java
core/src/test/java/io/confluent/rest/SslTest.java
pom.xml

- 1 don't have a single static thread pool that all FileWatchers use
- 2 update tests to cleanup temp/test keystore files
Also, introduced awaitility test library

 Make SslTest that verifies keystore reloading not flakey

---

pom.xml

Note that Jersey needs to be upgraded as well to ensure compatibility.
See this word of caution that was included in AK before this upgrade was applied 
https://github.com/apache/kafka/blob/dbdd1b1bb72ab0e012f7a746cefb6e593da44683/gradle/dependencies.gradle#L71

ST-4542: Upgrade jetty to address CVE-2020-27216

---

pom.xml

https://github.com/confluentinc/schema-registry takes Guava version from this parent. 
There is a CVE related to Guava: https://confluentinc.atlassian.net/jira/software/c/projects/FF/issues/FF-3928

ff-3928: bump version of Guava in parent of schema-registry.

---

core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/TestCustomizeThreadPool.java

* Ability to customize the thread pool and size of request queue.
**Why**
Backporting the change as we have customers who are asking for this for older supported versions of C3

(backport) SEC-592:  Customize Jetty request queue and threadpool size (#172)

---

core/pom.xml
pom.xml

Starting from `5.4.x`, jersey version 2.31 will have transitive dependencies on HibernateValidator versions `6.1.2.Final`. Upgrade HibernateValidator to `6.1.7.Final`.

upgrade hibernate-validator to 6.1.7.Final

---

pom.xml

We did it for 5.5.x and later: https://github.com/confluentinc/rest-utils/pull/215/files, this PR wants to fix back to 5.1.x when Guava first appears.

UIF-302: Upgrade guava for 5.4.x and older.

---

pom.xml

Before: this transitive dependency version of httpclient has a CVE
After: Upgrade org.apache.httpcomponents.httpclient to 4.5.13
Ref: https://confluentinc.atlassian.net/browse/UIF-300

UIF-300: Upgrade org.apache.httpcomponents.httpclient 

---

pom.xml

5.1.x ---- 5.5.x all use 24.1.1-jre version of Guava. Although Common uses 28.1, for the purpose of fixing Guava CVE, we do want to enforce all consumers of Rest-Utils to use 24.1.1-jre for now. It can be future work to sync Guava version.
This will only be in 5.0.x.

MMA-9930: Use compatible version of Guava

---

pom.xml

https://confluentinc.atlassian.net/browse/UIF-298 
This will fix 5.4.x and newer.
https://github.com/confluentinc/rest-utils/pull/219 will try to work on 5.3.x and older.

UIF-298: Upgrade Jetty to 9.4.35.v20201120

---

pom.xml

We have updated Jetty version to `9.4.36.v20210114` for kafka 2.4 and above versions.
This PR is to update Jetty version to `9.4.36.v20210114` to match with Kafka version.

KC-1456: Update Jetty to 9.4.36.v20210114

---

core/src/main/java/io/confluent/rest/Application.java

Jira: https://confluentinc.atlassian.net/browse/MMA-10032
**What**
Change the visibility of `configure handler` methods
**Why**
To allow hosting app to dynamically add/remove handlers at runtime from `Application` object

MMA-10032: Make configure handler methods public

---

core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

Why/How
-----
MDS in cloud is occasionally registering unknown exceptions. These were marked as "status unknown", and upon reading the kibana logs, they looked like 400s, not 500s. So I looked closer at how we emit this metric, and it looks like this accounting happens before any mappers are applied. Since a mapper could take any exception and set any status code, it's clear that this error accounting should happen after mappers (in the "Finished" event). Added bonus is now we can directly ask for the actual status code returned, rather than the weird type-casting.
Also added error logs in the event that we can't tell how to tag this exception, so we can study those cases in detail more easily.

CIAM-526 Count error codes after ExceptionMappers and use actual status code for all exception classes

---

pom.xml

Resolves #233.
This issue was [patched in 9.4.37.v20210219](https://github.com/eclipse/jetty.project/security/advisories/GHSA-m394-8rww-3jr7) and this PR updates Jetty dependency into the following version, 9.4.38.v20210224.

Update Jetty: 9.4.36.v20210114 → 9.4.38.v20210224

---

core/src/test/java/io/confluent/rest/SaslTest.java
core/src/test/java/io/confluent/rest/SslTest.java
core/src/test/java/io/confluent/rest/TestMetricsReporter.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

This addresses the deprecated API usages in `6.0.x` that will break after the first wave of Kafka 3.0.0 changes are merged in (the relevant discussion is available in Confluent's Slack).
- AFAICS, there's another set of usages that live just in `master`, related to the `5xx` metrics - I'll address these with a separate PR.
Tested by running all `rest-utils` tests locally.

KREST-860 Fix deprecated usages of org.apache.kafka.common.Metric.value()

---

core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

A follow-up to #239, addressing specifically a couple of usages that live just in `master`.

KREST-860 Fix deprecated usages of org.apache.kafka.common.Metric.value() in master

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/ApiHeadersTest.java
core/src/test/java/io/confluent/rest/CustomInitTest.java
core/src/test/java/io/confluent/rest/DosFilterTest.java
core/src/test/java/io/confluent/rest/ExceptionHandlingTest.java
core/src/test/java/io/confluent/rest/GzipHandlerIntegrationTest.java

This PR exposes per-application DosFilter support. See https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/servlets/DoSFilter.html for more information about the options available.
Config names are kept equal to the ones in Jetty's DosFilter. That unfortunately includes a usage of "whitelist", which otherwise would not meet Confluent's bar.

KREST-578: Add configurable DosFilter support.

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/FileWatcher.java
core/src/main/java/io/confluent/rest/MetricsListener.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/filters/CsrfTokenProtectionFilter.java
core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/main/java/io/confluent/rest/validation/ConstraintViolations.java
core/src/test/java/io/confluent/rest/ApplicationGroupTest.java
core/src/test/java/io/confluent/rest/ApplicationTest.java
core/src/test/java/io/confluent/rest/CsrfHandlingTest.java
core/src/test/java/io/confluent/rest/ExceptionHandlingTest.java
core/src/test/java/io/confluent/rest/GzipHandlerIntegrationTest.java
core/src/test/java/io/confluent/rest/SaslTest.java
core/src/test/java/io/confluent/rest/ShutdownTest.java
core/src/test/java/io/confluent/rest/SslTest.java
core/src/test/java/io/confluent/rest/StaticResourcesTest.java
core/src/test/java/io/confluent/rest/TestCustomizeThreadPool.java
core/src/test/java/io/confluent/rest/TestCustomizedHttpResponseHeaders.java
core/src/test/java/io/confluent/rest/TestMetricsReporter.java
core/src/test/java/io/confluent/rest/TestRestConfig.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java
core/src/test/java/io/confluent/rest/metrics/RequestScopedMetricsIntegrationTest.java
examples/src/main/java/io/confluent/rest/examples/helloworld/HelloWorldApplication.java
examples/src/main/java/io/confluent/rest/examples/helloworld/HelloWorldResource.java
test/src/main/java/io/confluent/rest/EmbeddedServerTestHarness.java
test/src/main/java/io/confluent/rest/Generics.java

Deprecation changes:
* `Slf4jRequestLog` ->  `CustomRequestLog`
* `configureContext` -> `initialize`
* `NetworkTrafficListener.Adapter` -> `NetworkTrafficListener`
* `ExpectedException` -> `assertThrows`
* `SSL_CLIENT_AUTH_CONFIG` -> `SSL_CLIENT_AUTHENTICATION_CONFIG`
* `Total` -> `CumulativeSum`
Other warnings/clean-ups:
* Various unchecked warnings: fixed the easy ones and added suppression for the rest
* Introduce `getPort` so that we can suppress usage of deprecated config in one place
* Use `assertNotEquals` instead of `assertTrue`
* Use `assertTrue` instead of `assertEquals` when expected result is `true`
* Remove unused variable
* Don't use static field as non-static
* Use diamond operator
* Remove unnecessary null check

Fix all compiler warnings (including deprecated usages)

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/exceptions/JsonMappingExceptionMapper.java
core/src/test/java/io/confluent/rest/JsonMappingExceptionMapperTest.java

fix https://github.com/confluentinc/rest-utils/issues/9
jira: https://confluentinc.atlassian.net/browse/DGS-1546
**Test**
Unit test added. 
**Example response**
```
% curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"schema": {}}' \
http://localhost:8081/subjects/Kafka-key/versions
{"error_code":400,"message":"Cannot deserialize instance of `java.lang.String` out of START_OBJECT token\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 12] (through reference chain: io.confluent.kafka.schemaregistry.client.rest.entities.requests.RegisterSchemaRequest[\"schema\"])"}%
```

DGS-1546 Map JsonMappingException to 400 response

---

pom.xml

Catch up with 5.5.x on Jetty version https://github.com/confluentinc/rest-utils/commit/2af4448a290fdca8ffc159796260c5ea3a9adc78

Upgrade Jetty to 9.4.39.v20210325

---

pom.xml

For
[cvss: 5.90 ] CVE-2021-21295 ['fixed in 4.1.60']
[cvss: 5.90 ] CVE-2021-21409 ['fixed in 4.1.61']
[cvss: 5.50 ] CVE-2021-21290 ['fixed in 4.1.59']

Bump netty-version 4.1.63

---

pom.xml

This netty version property is now defined in common so no need to have it defined here as well.

ST-5293: Cleanup of netty version property

---

core/pom.xml

The netty libraries are being loaded as a dependency of async-http-client, so I am excluding them from there and then explicitly loading the newer version we need to resolve the cve. I ran the tests several times to make sure they are all resolved. I also checked the dependency tree to make sure all netty libraries are on the same version.
[INFO] io.confluent:rest-utils-package:pom:6.2.0-0
[INFO] \- io.confluent:rest-utils:jar:6.2.0-0:compile
[INFO]    +- io.netty:netty-buffer:jar:4.1.63.Final:compile
[INFO]    |  \- io.netty:netty-common:jar:4.1.63.Final:compile
[INFO]    +- io.netty:netty-codec-http:jar:4.1.63.Final:compile
[INFO]    |  +- io.netty:netty-transport:jar:4.1.63.Final:compile
[INFO]    |  +- io.netty:netty-codec:jar:4.1.63.Final:compile
[INFO]    |  \- …

ST-5293: Explicit load of netty dependencies

---

core/src/test/java/io/confluent/rest/SslTest.java
pom.xml

Jira ticket: https://confluentinc.atlassian.net/browse/MMA-10473
For
[cvss: 5.90 ] [CVE-2018-10237](https://github.com/advisories/GHSA-mvr2-9pj6-7w5j) ['fixed in 24.1.1']
[cvss: 3.30 ] [CVE-2020-8908](https://github.com/advisories/GHSA-5mg8-w23w-74h3) ['fixed in 30.0']

bump guava version to 30.1.1-jre

---

core/pom.xml
core/src/main/java/io/confluent/rest/Application.java
core/src/test/java/io/confluent/rest/CustomInitTest.java
core/src/test/java/io/confluent/rest/SaslTest.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java
pom.xml

These two changes address multiple CVEs related to Jetty and Jersey (including an exclusion plus direct dependency for `hibernate-validator`).
They have already been introduced in `5.4.x` and above, but need to land in `5.2.x` and `5.3.x` too.
- See https://github.com/confluentinc/rest-utils/pull/224, https://github.com/confluentinc/rest-utils/pull/246 and https://github.com/confluentinc/rest-utils/pull/249 for the bumps to the latest versions on the higher branches.
- For the Jetty change, you also might want to check out #147, #151, and #155.
- There will be [a separate PR for `5.3.x`](https://github.com/confluentinc/rest-utils/pull/253) as there are conflicts when merging this there anyway.
- We do bump to the latest versions, very similar to the ones we're currently using in Apache …

KREST-1030 Upgrade Jetty and Jersey to address a number of CVEs

---

core/pom.xml
core/src/test/java/io/confluent/rest/CustomInitTest.java
core/src/test/java/io/confluent/rest/SaslTest.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java
pom.xml

See #252 - this merges the changes from there to `5.3.x`, fixing the conflicts along the way. It should then be merged up with `-s ours`, as #246 and #249 have already introduced these changes in `5.4.x` and up.
- If #252 is merged with "Rebase and merge", we should be able to push the changes from here without further rebasing.

KREST-1031 Upgrade Jetty and Jersey to address a number of CVEs

---

Makefile
create_archive.sh

Support new security patch release pattern.
Add new security suffix for packaging name.

ST-5057: security patch release support for archive

---

debian/Makefile
debian/create_archive.sh

Support new security patch release pattern.
Add new security suffix for packaging name.

ST-5057: security patch release support for debian

---

core/pom.xml
core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/Http2Test.java
pom.xml

Added support for HTTP/2 on Java 11 and later. Because HTTP/2 and ALPN are newer than Java 8, adding support for Java 8 as well is not practical. So, the behaviour is:
* If java 11 compatible
* if (http)
* configure HTTP and HTTP/2 Clear text connection factories
* else (https)
* configure SSL, ALPN, HTTP/2 and HTTP connection factories
* else as before
This means that when the code is running on a Java 11 JVM or later, connections will default to HTTP/2 not HTTP/1.1 if the client can support it. This change in behaviour is appropriate for the major version bump to CP 7.0 but not CP 6.x.
PR is marked as WIP because investigating the best way to introduce the dependency on the `jetty-alpn-java-server` package into the repos that depend on rest-utils.

KREST-661: Add support for HTTP/2 on Java 11 and later

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/DosFilterTest.java

Also removes dos.filter.track.session option, since Kafka REST does not use sessions, so that option has no effect.

KREST-1346: Add option to apply rate-limit globally across all connections.

---

core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/test/java/io/confluent/rest/Http2Test.java

There is a difference in URI handled between HTTP/1.1 and HTTP/2 in Jetty 9.4. Essentially, this is related to security and preventing malicious HTTP clients from using clever URIs containing / and .. from discovering information they have no right to obtain. So, Jetty 9.4 changed its behaviour to prevent use of these characters in URIs which then caused compatibility problems.
As a result, Jetty changed again so that HTTP/1.1 connections by default use a legacy HTTP compliance mode, implemented as a parameter to a constructor. HTTP/2 connections are not constructed in the same way and do not benefit from the same mechanism.
Nowadays rest-utils supports both HTTP/1.1 and HTTP/2. Any client that can support HTTP/2 gets that in preference to HTTP/1.1. Schema Registry users sometimes use …

KREST-1403: Set RFC7230 mode for connections

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/auth/AuthUtil.java
core/src/test/java/io/confluent/rest/ApplicationTest.java
core/src/test/java/io/confluent/rest/auth/AuthUtilTest.java

Using the sample application
REJECT_OPTIONS_REQUEST set to default (false)
% curl http://localhost:8080/hello -X OPTIONS
HEAD, GET, OPTIONS%                                                                                                                                                                           
REJECT_OPTIONS_REQUEST set to true
% curl http://localhost:8080/hello -X OPTIONS
% 
Tested with both no auth and basic auth enabled, as the code path is slightly different between the two.

Allow disabling OPTIONS on REST proxy

---

core/src/main/java/io/confluent/rest/Application.java

manually verified
request log changes from `GETsT` to a number that looks like request time
```
from
GET /test/endpoint HTTP/1.1" 200 21 "-" "curl/7.64.1" GETsT (io.confluent.rest-utils.requests:62)
to
GET /test/endpoint HTTP/1.1" 200 21 "-" "curl/7.64.1" 2 (io.confluent.rest-utils.requests:62)
```
I think `%{ms}T` is probably what was meant.   Request time in milliseconds.
* https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/server/CustomRequestLog.html
```
%{UNIT}T	The time taken to serve the request, in a time unit given by UNIT. Valid units are ms for milliseconds, us for microseconds, and s for seconds. Using s gives the same result as %T without any format; using us gives the same result as %D.
```

Fix request logger to print request time in milliseconds

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/CustomInitTest.java
core/src/test/java/io/confluent/rest/DosFilterTest.java
core/src/test/java/io/confluent/rest/ExceptionHandlingTest.java
core/src/test/java/io/confluent/rest/GzipHandlerIntegrationTest.java

Cherry pick of commit 51e387e to backport the fix to 5.2.x and later.
This PR exposes per-application DosFilter support. See https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/servlets/DoSFilter.html for more information about the options available.
Config names are kept equal to the ones in Jetty's DosFilter. That unfortunately includes a usage of "whitelist", which otherwise would not meet Confluent's bar.
This PR also changes several tests to use a random port, to avoid race conditions with port binding.

KREST-578: Add configurable DosFilter support. (#238)

---

core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

At present, rest-utils only collects rate based metrics.  Absolute metrics will also be useful.
This commit adds metrics to count, both cumulatively and also on a windowed basis:
- requests that finish successfully
- error status responses (for any error response)
- error status response, per grouping of errors.  The groupings are unknown, 1xx, 2xx, 3xx, 4xx and 5xx

KREST-1671 Add counter metrics

---

core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

When I first added the metrics I wasn't sure whether I needed the windowed count or the cumulative, so added both.
I can't think of an occasion where we want cumulative counts, and as suggested by Rigel, I'm removing them

KREST-1671 remove cumulative metric counts as we aren't using them

---

core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/test/java/io/confluent/rest/SslTest.java

This pull request adds a `SecureRequestCustomizer()` to the configuration in case SSL is set up. 
Without the `SecureRequestCustomizer()`, if a server-side application calls `.getScheme()` on incoming requests, it gets `http` even for HTTPS requests. 
Added a test to validate the behavior. 
Notes to reviewers: 
- This bug doesn't affect 6.2.x, which I have verified manually. The test passes when backported to 6.2.x without the need for an explicit customizer.
- The first commit in this PR is only the test but not the fix, so you can inspect that this is indeed an issue. The second commit adds the fix, so build no. 2 should pass.
- The exact reason that caused this change of behavior from `6.2.x` => `7.0.x` is still to be investigated.

SEC-2720: Add SecureRequestCustomizer for correct resolution of http vs https requests.

---

pom.xml

Upgrade Jersey to fix vulnerable jakarta.el:jakarta.el-api.

APIF-1690: Fix CVE-2021-28170

---

pom.xml

This is to make sure that all children will enforce io.netty:netty-codec at 4.1.68.Final version.

Enforce Netty for children

---

core/src/main/java/io/confluent/rest/exceptions/RestTimeoutException.java
core/src/main/java/io/confluent/rest/validation/JacksonMessageBodyProvider.java
core/src/test/java/io/confluent/rest/ExceptionHandlingTest.java

Catch TimeoutException and map to 408 when reading input stream from bad client
jira: https://confluentinc.atlassian.net/browse/DGS-2581

DGS-2581: Catch TimeoutException and map to 408 

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/DosFilterTest.java

Before this PR the code checked if the "global" rate limiter was turned on and if the "per port" configuration was set.  If so, the dos filters were applied globally, across all connections.  If not, a per connection rate limiter was created.
The global property is `dos.filter.track.global` which is set to true in cc-spec-kafka (although the in code default is false) and its intention is to do dos rate limiting across all connections, ie globally.
The per port property is `dos.filter.remote.port` which is set to false in cc-spec-kafka and also in code. The intent of this property is to apply the dos filters per ip-addres:port rather than just ip-address.
Before this PR, the dos filters were just applied globally, although the documentation for the `dos.filter.max.requests.per.sec` rate …

KREST-3148 enable ip based rate limiting

---

pom.xml

From 3.8.1, maven blocks [the HTTP repositories for CVE-2021-26291](https://maven.apache.org/docs/3.8.1/release-notes.html#cve-2021-26291) so rest-utils the build fails (below).
This PR fixes this issue by updating the repository configuration from http to https.

TRIVIAL: Change the Maven repository protocol: http → https

---

pom.xml

`rest-utils` uses http maven url in pom.xml. Downloading of artifacts over an interceptable channel like http is dangerous.
This PR pretty much copies the changes from #300 to `5.2.x` branch.

APIF-2005: Change the Maven repository protocol: http → https

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java

Jira: https://confluentinc.atlassian.net/browse/MMA-11468
**What**
In general, we need to ensure that Content-Type response header is set correctly for ALL response types along with X-Content-Type-Options: nosniff header. Setting correct values for Content-Type along with X-Content-Type-Options: nosniff header helps to defend against attacks based on MIME sniffing in browser and helps in triggering default protections in browsers against side-channel attacks like Spectre.

MMA-11468: Add option to enable nosniff protection

---

pom.xml

- 5.4.x: https://github.com/confluentinc/common/blob/5.4.x/pom.xml#L83
- 5.5.x: https://github.com/confluentinc/common/blob/5.5.x/pom.xml#L84
- 6.0.x: https://github.com/confluentinc/common/blob/6.0.x/pom.xml#L88
- 6.1.x: https://github.com/confluentinc/common/blob/6.1.x/pom.xml#L88
- 6.2.x: https://github.com/confluentinc/common/blob/6.2.x/pom.xml#L88
- 7.0.x: https://github.com/confluentinc/common/blob/7.0.x/pom.xml#L88
- 7.1.x: https://github.com/confluentinc/common/blob/7.1.x/pom.xml#L89
- master:https://github.com/confluentinc/common/blob/master/pom.xml#L89
Its version has already been defined in common, which is parent for rest-utils. This will save future work on fixing netty versions.

Remove Redundant Netty Definition

---

core/pom.xml
pom.xml
test/pom.xml

Running mvn dependency:tree shows that jersey pulls in junit 4.
There's no version of jersey that ships junit 5, but compatibility for using it came in at jersey 2.35, so I've updated the version and excluded junit4
https://github.com/eclipse-ee4j/jersey/pull/4824

KREST-3660 Remove junit 4 dependencies that come in via jersey test

---

core/pom.xml

This is to override the netty version of two packages: 
-  io.netty:netty-codec
-  io.netty:netty-codec-http
This is to resolve CVEs:
- [CVE-2021-37136](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-37136)
- [CVE-2021-37137](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-37136)
- CVE-2021-43797
These were packaged into confluent-security-plugins.

APPSEC-725:Override netty in 7.1.x only

---

.github/CODEOWNERS

The official owners of rest-utils are cloud-foundations, however kafka-rest make many changes in this repo too, and have a good understanding of what's OK to PR and what isn't.
At the moment we need the cloud-foundations team to sign off any changes we make, I think kafka-rest need this ability too.
Updating codeowners file.

KREST-4958 Update codeowners to also include kafka-rest

---

core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/test/java/io/confluent/rest/ApplicationServerTest.java

This minimum calculation is copied for the jetty code which uses the same formula when no request queue is configured (which is actually the recommened way of starting up the application).

KREST-3446 ensure there is always a minimum value for the thread pool queue

---

core/src/main/java/io/confluent/rest/exceptions/KafkaExceptionMapper.java
core/src/test/java/io/confluent/rest/KafkaExceptionMapperTest.java

This is a user error - they've specified a topic that doesn't exist, not a server error
So the return code should be a 4xx variant, not a 5xx variant.
Tested in a running kafka-rest
< HTTP/1.1 200 OK
< Date: Thu, 14 Apr 2022 12:41:17 GMT
< Content-Type: application/json
< Vary: Accept-Encoding, User-Agent
< Transfer-Encoding: chunked
<
{"error_code":40401,"message":"Topic eric not present in metadata after 60000 ms."}
* Connection #0 to host localhost left intact
* Closing connection 0

KREST-4450 500 error when topic not present

---

core/pom.xml
examples/pom.xml

Switch from confluent-log4j to reload4j. Used https://github.com/confluentinc/ksql/pull/9065/files as an example.
```
➜  rest-utils git:(fix-slf4j-log4j123) mvn dependency:tree -Dincludes=org.slf4j:slf4j-log4j12
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.bitness: 64
[INFO] os.detected.version: 10.15
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 15
[INFO] os.detected.classifier: osx-x86_64
[INFO] ------------------------------------------------------------------------
[INFO] Reactor …
```

Switch from confluent-log4j to reload4j 

---

core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/ConnectionLimitTest.java

This change enables configurable on startup connection limiting per server and per connector based on Jetty's `ConnectionLimit` listener (see its [Javadoc](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/server/ConnectionLimit.html) and [this Jetty issue about its usage](https://github.com/eclipse/jetty.project/issues/2501#issue-319785646)).
That mechanism allows limiting the number of active connections (already opened + currently being opened) connections as with long-running connections, like with Kafka REST's Produce v3 streams, rate limits don't guarantee that we won't have an accumulation of connections past what the server can withstand.
This has been tested locally via the aforementioned Kafka REST Produce v3 streams.
After setting `server.connection.limit=3` and …

KREST-4977 Allow limiting the number of active connections.

---

pom.xml

```
[INFO] io.confluent.controlcenter:control-center:jar:5.4.9-SNAPSHOT
[INFO] \- io.confluent:rest-utils:jar:5.4.9-SNAPSHOT:compile
[INFO]    \- org.eclipse.jetty:jetty-server:jar:9.4.44.v20210927:compile
[INFO]       \- org.eclipse.jetty:jetty-http:jar:9.4.44.v20210927:compile
```
```
[INFO] io.confluent.controlcenter:control-center:jar:5.4.9-SNAPSHOT
[INFO] \- io.confluent:rest-utils:jar:5.4.9-SNAPSHOT:compile
[INFO]    \- org.eclipse.jetty:jetty-server:jar:9.4.48.v20220622:compile
[INFO]       \- org.eclipse.jetty:jetty-http:jar:9.4.48.v20220622:compile
```
https://confluentinc.atlassian.net/browse/MMA-12212

[MMA-12212] Bump jetty version to 9.4.48.v20220622

---

pom.xml

This upgrade needs to go piece by piece (for individual), reverting to previous version for now.
This reverts commit 8eb6333cc4dd1844807a66b06bb93a5f15715450.

Revert "[MMA-12212] Bump jetty version to 9.4.48.v20220622 (#330)"

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/errorhandlers/NoJettyDefaultStackTraceErrorHandler.java
core/src/test/java/io/confluent/rest/CsrfHandlingTest.java
core/src/test/java/io/confluent/rest/ErrorHandlerIntegrationTest.java

An issue was noticed where any unhandled exceptions thrown by Jetty Handlers display the stack trace of the exception to the user. For internal server errors we should avoid showing stack traces to the user as it poses a security risk. The StackTraceErrorHandler removes stack traces and servlet information before passing response to user and is optional by consumers of the rest-utils library.

ErrorHandler to suppress the default Jetty behavior of printing full stacktraces for 500s

---

core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

This PR tries to fix the bug that a sensor created for a method + performance annotation pair is shared across the entire application, as opposed to each request tag set having its own copy of sensor. It is causing a problem when request tags are used. A sensor is either created or fetched depending on whether the name exists. For example, 
1. `methodX.request-size` sensor is created on application startup, let's call it sensorA
2. a request w/ tag1 comes in, sensorA is returned because the same sensor name is provided
3. a request w/ tag2 comes in, sensorA is again returned
However, each tag really should have its own sensor.
The fix sorts request tags to make sure the same sensor is used for the same set of request tags. Tags in `MetricName` is also sorted for `JmxReporter` to create …

DGS-4220: fix request tag based metrics

---

core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

We need a cumulative counter to report request count, rather than the existing windowed/sampled count. The potential issue with windowed count is discussed [here](https://github.com/confluentinc/rest-utils/issues/344), which will not be addressed in this PR.

MINOR: Add request cumulative counter in MetricsResourceMethodApplicationListener

---

core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

Address https://github.com/confluentinc/rest-utils/issues/344#issuecomment-1204155953

MINOR: Rename metric in MetricsResourceMethodApplicationListener

---

pom.xml

Address CVE-2022-2047.
This PR needs to be merged together with https://github.com/confluentinc/ce-kafka/pull/7068, to avoid issues with conflicting jars.

APIF-2739: Upgrade Jetty to 9.4.48.v20220622.

---

Jenkinsfile
pom.xml

This PR adds `pinnedNanoVersions` property, so that project will try to pin each upstream version update in pom.xml instead of using version range which always selects the latest version.
e.g.
[7.3.0, 7.4.0) -> 7.3.0-99 after each build
- better reproducible builds, master/release branch won't follow latest upstream dependency because of version range. Local build dependencies can be traced more easily.
- branch become more stable since it will reject broken changes from upstream.
- version bump commit will be serperated from actual code change so that broken change can be targeted easily.
The current git workflow:
That is brought up by Ksql team initially because they want to have better reproducible builds. And with that change, version bumps will only happen when the upstream build is …

chore: Switch to pinned nanoversion strategy

---

core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java

This will give greater precision when latency is closer to zero
(and less precision when it's further). With 200 buckets to cover
10 seconds, CONSTANT sizing gave no precision below 50 ms.
Ref: https://github.com/confluentinc/ce-kafka/blob/5f154af1ffc138ac5ab7b4de1829e3c247f32015/clients/src/main/java/org/apache/kafka/common/metrics/stats/Histogram.java#L164-L168

Use LINEAR instead of CONSTANT bucket sizing for latency percentiles.

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/NamedURI.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/SslClientAuth.java
core/src/main/java/io/confluent/rest/SslConfig.java
core/src/main/java/io/confluent/rest/SslFactory.java
core/src/test/java/io/confluent/rest/ApplicationServerTest.java
core/src/test/java/io/confluent/rest/ApplicationTest.java

This PR prepares the rest-utils API for per-listener SSL configs. Changes:
* [new] `SslConfig`: This class encapsulates the many SSL params in rest-utils.
* [new] `SslFactory`: `ApplicationServer.createSslContextFactory` method extracted out.
* Moved all the listener parsing logic from `ApplicationServer` to `RestConfig`.
* [new] `RestConfig.getBaseSslConfig()`: Returns the unprefixed (base) SSL configs.
* [new] `RestConfig.getSslConfigs()`: Returns the per-listener SSL configs.
Note that this PR does not implements per-listener SSL config. It only introduces the APIs, so that downstream applications can adapt before the changes. As such, all the SSL configs returned are the same for all listeners.

APIF-2959: Prepare rest-utils API for per-listener SSL configs.

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/ApplicationServer.java

And use it to configure the per-listener SSL factories, even if they are all the same.
This is needed so that https://github.com/confluentinc/blueway/pull/2445 works without changing behaviour on C3 backend.

Add ApplicationServer.getSslContextFactories method.

---

core/src/main/java/io/confluent/rest/NamedURI.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/RestConfigTest.java

`ApplicationServer` already has the ability to specify listener names in the `listeners` config. This PR adds the ability to specify per-listener-name overrides for the SSL configs only (i.e. configs starting with `ssl.`, no other config affected).
The way to do that is by setting the config `listener.name.<listener-name>.<ssl-config>` instead of `<ssl-config>`. If you set `<ssl-config>`, that will be treated as the default value for `listener.name.<listener-name>.<ssl-config>` for all listeners. Example:
```
// Config
listeners=A://1.1.1.1:1,B://2.2.2.2:2
listener.protocol.map=A:https,B:https
ssl.keystore.location=default.jks
listener.name.A.ssl.keystore.location=a.jks
// Means
// For listener https://1.1.1.1:1
ssl.keystore.location=a.jks
// For listener https://2.2.2.2:2 …
```

APIF-2959: Add support for per-listener SSL config.

---

core/src/main/java/io/confluent/rest/Application.java

We use two jetty DOS rate limiters - a global (all ips) one and a per connection one.
These were registered backwards - the global one first and then the per connection one.
This meant that if someone was spamming our endpoints, the global limiter's requests were all used up before the per connection one could take effect.
Jetty maintains the order of the filters registered, so if we register the per connection one first, that will get rid of the too many connections from a single ip issue.
I've tested this locally using curl with the --resolve option.  Requests from 127.0.0.1 in a tight loop get rate limited, and requests from my ip address that go through at a much slower rate do not.
There is a slight concern that the list of ip addresses held by the dos filter might get too long, but …

KREST-8391 swap order of dos rate limiters

---

core/src/test/java/io/confluent/rest/KafkaExceptionMapperTest.java

- in KAFKA-14417 ConcurrentTransactionsException was changed from an ApiException to be a RetriableException (which is itself an ApiException)
- Doing if/else logic based on instanceof check so the test can handle the ConcurrentTransactionsException being of either heritage as Jenkins sees the updated class but my local build only sees the old one

Adapt Test to handle Exception class changing its parent

---

core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/ApplicationServerTest.java

One of the query parameters for the rbac list endpoints is getting too large (it is a list of all the internal service accounts in an org). As a quick fix, make the jetty response/request max header size configurable in `ApplicationServer`.

CIAM-2420: Add max buffer header size configs

---

core/pom.xml
core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/SslConfig.java
core/src/main/java/io/confluent/rest/SslFactory.java
core/src/test/java/io/confluent/rest/Http2Test.java
pom.xml

Adding jetty to uses [Conscrypt](https://github.com/google/conscrypt) TLS Engine as well which is based on BoringSSL and provides better TLS performance. Also with Conscrypt [HTTP/2 with Jetty can be supported over JDK 8](https://github.com/jetty-project/jetty.project/blob/e89b985fd59928d3f0432bddf38991977366d85c/documentation/jetty-documentation/src/main/asciidoc/old_docs/alpn/alpn.adoc#L35) as well.
Configuration needed:
```
ssl.protocol=TLSv1.3
ssl.provider=Conscrypt
```
The changes were tested with `Java 8` and `Java 17` in `HTTP/2` `enabled/disabled` mode and `with/without` `Conscrypt` TLS provider. 
```
[2023-03-06 13:05:01,649] DEBUG Matched SNI localhost with alias kafka-rest, certificate X509@4364712f(kafka-rest,h=[localhost, kafka-rest],a=[/127.0.0.1],w=[]) from aliases …
```

Add BoringSSL TLS provider with Conscrypt

---

core/src/main/java/io/confluent/rest/SslFactory.java

- Conscrypt is not yet supported on AARCH64 architecture hence eager loading of library causes issue. Defer load until ssl provider explicitly specifies. 
- Supported platforms are mentioned here: https://github.com/google/conscrypt/#native-classifiers
- Change has been tested on server with `arm64` arch.

Defer loading Conscrypt library

---

core/src/main/java/io/confluent/rest/exceptions/KafkaExceptionMapper.java
core/src/test/java/io/confluent/rest/KafkaExceptionMapperTest.java

This is kafka exception is raised due to bad user input, hence should be returned as a 400, instead of a 500(server error).

KREST 9773 Handle InvalidTopicException correctly

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/errorhandlers/NoJettyDefaultStackTraceErrorHandler.java
core/src/test/java/io/confluent/rest/ErrorHandlerIntegrationTest.java

This will make the response nicer, in term of no stack trace will show up for error on server

Remove stacktrace in response when server throws BadMessageException

---

core/src/main/java/io/confluent/rest/Application.java
core/src/test/java/io/confluent/rest/ErrorHandlerIntegrationTest.java
core/src/test/java/io/confluent/rest/RequestLogHandlerIntegrationTest.java
core/src/test/java/io/confluent/rest/TestUtils.java

The issue comes from the RequestLogHandler is attached to the application server but not the serverlet context handler of the application. This will duplicate the log for all the applications on the server.
The fix is simply attaching RequestLogHandler to the context handler.

Insert RequestLogHandler to the ServletContextHandler instead of putting in Handler collection

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

What is it about?
---
This is to collect server-side metrics for [AUTHN-1586](https://confluentinc.atlassian.net/browse/AUTHN-1586), and is useful if others need it.
Add optional metrics about the count of requests that meet or violate latency SLO/SLA in the `Performance` annotation. 
How?
---
Add three config parameters.
1. (boolean) `METRICS_ENABLE_LATENCY_SLO_SLA_CONFIG`
2. (long) `METRICS_LATENCY_SLO_MS_CONFIG`
3. (long) `METRICS_LATENCY_SLA_MS_CONFIG`
If `METRICS_ENABLE_LATENCY_SLO_SLA_CONFIG` is enabled, add four sensors to count the number of request whose response latency below(above) SLO(SLA) threshold.
[AUTHN-1586]: https://confluentinc.atlassian.net/browse/AUTHN-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUTHN-1586 Add optional latency SLO/SLA metrics in annotation

---

core/src/main/java/io/confluent/rest/metrics/Jetty429MetricsDosFilterListener.java

The default function DosFilter.Listener.onRequestOverLimit will log this line 
```
[WARN] 2023-05-11 09:36:40,954 [qtp787738572-1439] org.eclipse.jetty.servlets.DoSFilter - DOS ALERT: Request rejected ip=127.0.0.1, overlimit=OverLimit@11dd96d5[type=IP, id=127.0.0.1, duration=PT0.361698758S, count=100], session=null, user=null
```
whenever a request is overlimited by DosFilter, this add unnecessary verbosity.
This PR disables this log line programmatically.
There is an alternative to disable this log line is by setting log level of `org.eclipse.jetty.servlets.DoSFilter` class to ERROR level.

Don't use DosFilter.Listener.onRequestOverLimit default to avoid verbosity

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/JettyDosFilterMultiListener.java
core/src/test/java/io/confluent/rest/JettyDosFilterMultiListenerIntegrationTest.java
core/src/test/java/io/confluent/rest/JettyDosFilterMultiListenerTest.java

This PR introduces 2 changes majorly
1. `JettyDosFilterMultiListener` is type of `DosFilter.Listener` that can hold multiple such listeners and run them. This is needed as Jetty's `DosFilter.setListener()` only accepts and runs `1 listener`. Whereas Kafka-rest needs to run another listener, other than the common one for all apps `Jetty429MetricsDosFilterListener`. This other listener will add metadata to the `HttpServletRequest` for custom-logging enhancement for kafka-rest(to be followed in another PR).
* `Application` exposes setters to set-up multi-listeners for the global & non-global dos-filters.
2. `Application`'s `requestLog` was final. Make it non-final, so child-applications can reset it, if needed. This would be used by `KafkaRestApplication` in `kafka-rest`.

KREST-10243 Add ability to run multiple dosfilter-listeners and setup a custom-log on the app.

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

This PR introduces a request attribute `GLOBAL_STATS_REQUEST_TAGS_ENABLED_PROP_KEY` to enable global stats (metrics for all resource methods) to include runtime tags from the requests. 
This will enable us to have tenant metrics whenever tenant tag is set in application resources (from ce-kafka-rest) for example.
This attributes is also used to keep the compatibility with all downstream apps that use `rest-utils`.
PR for `ce-kafka-rest` will be followup after this.

Introduce request attribute to enable global metrics use runtime request tags

---

core/src/main/java/io/confluent/rest/exceptions/KafkaExceptionMapper.java
core/src/test/java/io/confluent/rest/KafkaExceptionMapperTest.java

`TopicDeletionDisabledException` is only thrown by broker if
1. Its topic-deletion is disabled all together on user's kafka-cluster(uncommon setting).
2. Its a mirrored-topic, so can't be explicitly deleted.
In both cases, its a user-error, should be treated as such with `400` by kafka-rest

KREST-10790 Handle TopicDeletionDisabledException as 400

---

core/src/main/java/io/confluent/rest/exceptions/KafkaExceptionMapper.java
core/src/test/java/io/confluent/rest/KafkaExceptionMapperTest.java

ThrottlingQuotaExceededException denotes quota breach. This error code should be treated as 429 instead of 500.

KREST-10989: Handle ThrottlingQuotaExceededException exception as 429

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/metrics/JettyRequestMetricsFilter.java
core/src/main/java/io/confluent/rest/metrics/MetricNameUtil.java
core/src/test/java/io/confluent/rest/metrics/JettyRequestMetricsFilterIntegrationTest.java
core/src/test/java/io/confluent/rest/metrics/JettyRequestMetricsFilterTest.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

This PR uses a Filter as a mean to collect requests metrics on Jetty layer.

Add JettyRequestMetricsFilter for counting requests on Jetty layer

---

core/src/main/java/io/confluent/rest/exceptions/ConstraintViolationExceptionMapper.java
core/src/main/java/io/confluent/rest/exceptions/DebuggableExceptionMapper.java
core/src/main/java/io/confluent/rest/exceptions/JsonMappingExceptionMapper.java
core/src/main/java/io/confluent/rest/exceptions/JsonParseExceptionMapper.java
core/src/main/java/io/confluent/rest/exceptions/KafkaExceptionMapper.java
core/src/test/java/io/confluent/rest/ErrorMessageIntegrationTest.java
core/src/test/java/io/confluent/rest/JsonMappingExceptionMapperTest.java
core/src/test/java/io/confluent/rest/JsonParseExceptionMapperTest.java
core/src/test/java/io/confluent/rest/KafkaExceptionMapperTest.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

As title said, this makes sure that we explicitly specify application/json media type for ErrorMessage, otherwise, with Options request, it can return 500

Make sure that ErrorMessage is always interpreted as json in Response

---

core/pom.xml
core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/RateLimitNetworkTrafficListener.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/ratelimit/NetworkTrafficRateLimitBackend.java
core/src/main/java/io/confluent/rest/ratelimit/NetworkTrafficRateLimiter.java
core/src/main/java/io/confluent/rest/ratelimit/NetworkTrafficRateLimiterFactory.java
core/src/test/java/io/confluent/rest/RateLimitNetworkTrafficListenerTest.java
pom.xml

This PR implements a method to slowdown the reading rate from HTTP/TCP socket in Jetty. The approach is based on the fact that we can use NetworkTrafficListener to count for the reading from TCP sockets on all connections. This introduces 3 new configurations (there will be changed in cc-spec-kafka):
1. `network.traffic.rate.limit.enable`: whether to enable this rate limit
2. `network.traffic.rate.limit.backend`: backend of rate limiting, either guava or resilience4j
3. `network.traffic.rate.limit.bytes.per.sec`: the rate to limit, default to 20MiB
Reference JIRA https://confluentinc.atlassian.net/browse/KREST-11222

Implementation of RateLimitNetworkTrafficListener

---

core/src/main/java/io/confluent/rest/FileWatcher.java

Though Multiple FileWatchers are created for multiple listeners but they execute on `static` single thread pool. As the `run` method continuously executes hence only one among multiple submitted FileWatcher will run.
```
jmap -histo 1 | grep -e FileWatcher
4360:             2             64  io.confluent.rest.FileWatcher
8205:             1             16  io.confluent.rest.FileWatcher$1
```
When SslFactory registers multiple listeners for cert dynamic reload then only one among listener will get new certificate.
Current PR creates individual thread executor which guarantees execution of all FileWatcher and cert reload on all listener. 
We might do better here in future with registering all file change notifications. Rather than creating multiple file watcher services we can register for …

KREST-11276 - Fixing cert reload with multiple registered listeners

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/handlers/SniHandler.java
core/src/test/java/io/confluent/rest/SniHandlerIntegrationTest.java

This PR adds SniHandler that checks for SNI against the host of the request, if they don't match, response with 421.
This handler is controlled by configuration to turn off/on, default is disabled.
`sni.check.enabled`
[Jira ticket](https://confluentinc.atlassian.net/browse/KREST-7955)

KREST-7955 421 misdirected request if host does not match SNI

---

core/src/main/java/io/confluent/rest/FileWatcher.java
core/src/main/java/io/confluent/rest/SslFactory.java
core/src/test/java/io/confluent/rest/SslCertReloadTest.java
core/src/test/java/io/confluent/rest/SslTest.java

SR had an issue in devel where pods had to be restarted for it to pick up the renewed SSL certs. SR uses two listeners: 
https://github.com/confluentinc/cc-spec-schemaregistry/blob/050541fa3c02cacbe262bd8660da7b9d6aeac620/plugins/schemaregistry/templates/serverConfig.tmpl#L13
Cherry pick these two SSL cert loading improvement commits to `7.4.x`:
- KREST-11276 - Fixing cert reload with multiple registered listeners https://github.com/confluentinc/rest-utils/commit/7f5c03cdea2fa605138fd4fbae7cef17f8a2fca1
- KREST-11276 - Tighten SSL auto cert reload https://github.com/confluentinc/rest-utils/commit/d17f46b5e5f9a91735708f7872817a96d47b5bf8
I will `pint merge` this up from 7.4.x
Slack thread: https://confluent.slack.com/archives/C012SG54VM1/p1693434130502999

DGS-8180: Cherry pic SSL cert loading improvements from master

---

pom.xml

Jetty version is defined in common. Unpin the version here and use the one defined globally

CNC-397: unpin jetty to use the version defined in common

---

core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java

We have been getting paged once or twice every week of latency metrics that fire. When investigating usually these metrics are completely off. The root cause of the issue is the way we calculate the latency metric where the start time is stamped after resource matching. If we have filters that execute before matching, then the start time is not stamped and at the end when global metrics are calculated:
`final long elapsed = time.milliseconds() - started;`
The final time is just the current elapsed time since epoch. To fix this we need to move the start time stamping before resource matching. https://eclipse-ee4j.github.io/jersey.github.io/apidocs/2.34/jersey/org/glassfish/jersey/server/monitoring/ApplicationEventListener.html#onRequest-org.glassfish.jersey.server.monitoring.RequestEvent- …

CIAM-2673: initialize start time in metrics before onEvent() is called

---

.semaphore/project.yml
.semaphore/semaphore.yml
service.yml

Migration from Jenkins to Semaphore, for release branches, cherry-pick commits as instructed [here](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#I-only-see-changes-for-master.-How-do-I-apply-to-release-branches%3F)

KRES-12288 migration semaphore release branches

---

.semaphore/project.yml
.semaphore/semaphore.yml
service.yml

For some reason, pint-merge completely miss this branch for [this](https://github.com/confluentinc/rest-utils/pull/427), raise this manually to fix.

KREST-12288 semaphore migration to release branches

---

core/pom.xml

Update bouncycastle to version > 1.70. 
This PR needs to be re-tested after the merge of the change in common 
https://github.com/confluentinc/common/pull/565/checks?check_run_id=18759464892

KREST-12364: update bcpix

---

core/src/main/java/io/confluent/rest/exceptions/DebuggableExceptionMapper.java

Remove logging of exceptions for 404. This stack-trace is confusing in the logs as it is being logged for client issues.
But logging exceptions in 5xx is useful for debugging server-side issues.

KREST-12628 only log exceptions for 5xx

---

core/src/main/java/io/confluent/rest/SslFactory.java
core/src/test/java/io/confluent/rest/SslTest.java

Add a test that when `ssl.cipher.suite` is set to restrict ssl ciphers, only restricted ciphers work with REST.

KREST-13041 Test that SSL cipher suites can be restricted

---

Jenkinsfile

This PR removes the confluent-cloud-plugins and confluent-security-plugins repos as downstream repos in Jenkinsfile file (leaving them as downstream repos in service.yml/Semaphore). This change allows confluent-cloud-plugins and confluent-security-plugins to deprecate Jenkins without causing this repos downstream build to fail. A similar change to was made here: https://github.com/confluentinc/rest-utils/pull/443 to remove schema-registry from the Jenkinsfile.

Remove confluent-cloud-plugins and confluent-security-plugins as downstream in Jenkinsfile

---

service.yml

Part of migrating kafka-streams-examples from Jenkins to semaphore.
In Jenkins, we were use `upstreamProjects` to make sure that `kafka-streams-examples` is rebuilt when `rest-utils` is updated. See this line: [confluentinc/kafka-streams-examples@master/Jenkinsfile#L7](https://github.com/confluentinc/kafka-streams-examples/blob/master/Jenkinsfile?rgh-link-date=2024-01-10T10%3A26%3A16Z#L7)
This is not supported by the new semaphore tooling. Instead, we need to list `kafka-streams-examples` in the `downstream-projects` of `rest-utils`, see the feature gap section of the migration guide:
[confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#Features-gaps](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore …

KSTREAMS-5725: Make kafka-streams-examples a downsteam project of rest-utils

---

core/src/main/java/io/confluent/rest/exceptions/KafkaExceptionMapper.java

A 500 internal server error should be considered unusual, and so be followed up on.
We have 1 case in our logs, where the reason for the 500 is not written to logs, so I've added a line to show which timeout exception is causing the issue so that we have more of a change of diagnosing what's gone wrong

KREST-13506 Ensure we log timeout errors that result in a 500 error

---

Jenkinsfile

PR build is with JDK17 while master build is with JDK8 on Jenkins, this creates a gap where we have this test `SslTest.test_WhenCalledWithRestrictedCipher_ConnFails` consistently fails in [Jenkins](https://jenkins.confluent.io/job/confluentinc/job/rest-utils/job/master/9796/console) while it passes in PRs. Attempt to reproduce this failure in local machine is also unsuccessful (it passes with JDK8 on my Macbook).
Therefore, it is better just set the same JDK across PRs and master builds, also we're migrating from Jenkins to Semaphore (which uses JDK17 by default) anyway, so this is to reduce the toll of oncall resolving failed builds.

Set nodeLabel for nightly master build

---

fips-tests/pom.xml
fips-tests/src/test/java/io/confluent/rest/SslFactoryFipsTest.java

We have problem in CP packaging that fips-tests module needs rest-utils jar in order to compile, but in CP packaging rest-utils is compiled with `mvn -Dmaven.test.skip=true`, so no test jar is produced (because we don't release package with test jar), which breaks the build.
This PR breaks the deadlock by removing test jar dependency from fips-tests with the price of we have similar test code between `SslFactoryTest` and `SslFactoryFipsTest`.
However, there is no much we can do on this as fips and non-fips cannot be used together in a module.

Remove test jar dependency from fips-tests module

---

core/src/test/java/io/confluent/rest/SslFactoryTest.java
fips-tests/src/test/java/io/confluent/rest/SslFactoryFipsTest.java

Since https://github.com/confluentinc/rest-utils/pull/468, it is recommended that we need to keep tests insync for two classes SslFactoryFipsTest and SslFactoryTest

Add comment about keeping SslFactoryTest and SslFactoryFipsTest tests insync

---

core/pom.xml
core/src/main/java/io/confluent/rest/alpn/server/BouncyCastleServerALPNProcessor.java
fips-tests/pom.xml
fips-tests/src/test/java/io/confluent/rest/Http2FipsTest.java
fips-tests/src/test/java/io/confluent/rest/TestSslUtils.java

It has been found that with BouncyCastle (bc) SSL provider FIPS driver, Jetty HTTP2 isn't working because there isn't ALPNProcessor.Server service available.
```
java.lang.IllegalStateException: Connection rejected: No ALPN Processor for org.bouncycastle.jsse.provider.ProvSSLEngine_9 from [org.eclipse.jetty.alpn.java.server.JDK9ServerALPNProcessor@36def543]
at org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory.newServerConnection(ALPNServerConnectionFactory.java:111)
at org.eclipse.jetty.server.NegotiatingServerConnectionFactory.newConnection(NegotiatingServerConnectionFactory.java:108)
at org.eclipse.jetty.server.SslConnectionFactory.newConnection(SslConnectionFactory.java:131)
at org.eclipse.jetty.server.ServerConnector$ServerConnectorManager.newConnection(ServerConnector.java:618 …
```

FEDRAMP-5315 Support HTTP/2 for BouncyCastle FIPS enabled (#472)

---

pom.xml

Downgrade jetty to `9.4.53`
Commons jetty version was upgraded to `9.4.54` recently: https://github.com/confluentinc/common/pull/582 which affects userId/tenant based DoS filters in this repo.
Dependencies after the downgrade:
```
❯ mvn dependency:tree -Dincludes=org.eclipse.jetty
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: aarch_64
[INFO] os.detected.bitness: 64
[INFO] os.detected.version: 14.3
[INFO] os.detected.version.major: 14
[INFO] os.detected.version.minor: 3
[INFO] os.detected.classifier: osx-aarch_64
[INFO] …
```

Downgrade jetty package

---

pom.xml

#478 downgraded `jetty`, which has a vulnerability: [CVE-2023-36478](https://github.com/advisories/GHSA-wgh7-54f2-x98r). This PR reverts #478 and only downgrades `jetty-servlets`.
Dependencies after this change:
```
❯ mvn dependency:tree -Dincludes=org.eclipse.jetty
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: aarch_64
[INFO] os.detected.bitness: 64
[INFO] os.detected.version: 14.3
[INFO] os.detected.version.major: 14
[INFO] os.detected.version.minor: 3
[INFO] os.detected.classifier: osx-aarch_64
[INFO] …
```

Downgrade jetty-servlets package

---

core/src/test/java/io/confluent/rest/RequestLogHandlerIntegrationTest.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java
fips-tests/src/test/java/io/confluent/rest/Http2FipsTest.java

There are 2 kinds of flake are disabled in this PR:
- Pure flaky (pass locally but failed occasionally in CI), in `RequestLogHandlerIntegrationTest#test_CustomRequestLog_registeredToCorrectListener` and `MetricsResourceMethodApplicationListenerIntegrationTest#testMetricLatencySloSlaEnabled` 
- CI builder/upstream behaviour change (also pass locally and there isn't easy way to reproduce locally), in `Http2FipsTest`, CI was running all fine until this [build](https://semaphore.ci.confluent.io/workflows/6430372a-191f-4058-ae34-fb5d6786076c?pipeline_id=60c5681c-7fb5-429c-9dd7-444de133f38b), when all of a sudden, it starts to fail consistently. There is no change to rest-utils, so the suspect could be CI env change or upstream change.
Created a JIRA (in Disabled tag) to resolve those flaky …

Disable flaky tests

---

core/src/main/java/io/confluent/rest/ApplicationServer.java

In CP, there could be Metadata http server applications configured alongside with Kafka rest, therefore, the `ConfigException` will always throw because there is no NetworkTrafficServerConnector configured for Metadata http server application.
So we log a warn line instead.

Do not throw ConfigException in case there are different applications configured for the server

---

core/src/test/java/io/confluent/rest/RequestLogHandlerIntegrationTest.java

https://github.com/confluentinc/rest-utils/commit/da1d8d4387f60fc38d274634ad5bcb4f4d6a7f45#diff-cf9023bb601aa95ba939f1c04b13836f88c2bf59017e769dea7f1b0c00288a50
https://confluent.slack.com/archives/C06CFQNK2BF/p1717418329306549?thread_ts=1717169007.420509&cid=C06CFQNK2BF
I didn't want to cherry-pick the commit above, as the other changes are only in files in either master or 7.5.x onwards
Test failure originally is https://semaphore.ci.confluent.io/workflows/ec3b0361-84ed-4df9-ba09-ebb655e6bfcd/summary?report_id=17990af8-cb17-371c-9a8e-215e0e201902 in 7.5.x, but I'll bring this disable right back to the beginning to avoid other releases flaking

Fix flakey test similar to

---

core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/test/java/io/confluent/rest/HstsIntegrationTest.java

This PR adds a configuration to RestConfig `hsts.header.enable` that controls whether we response with HTTP Strict-Transport-Security (HSTS) header.

Add configuration hsts.header.enable to control whether we response with HSTS header

---

.semaphore/semaphore.yml

This PR adds cp jar build task invocation for PR builds to make sure downstream components don't break with the PR changes.

CPBR-1680: adding cp-jar-build block for PR builds

---

core/src/main/java/io/confluent/rest/Application.java
core/src/test/java/io/confluent/rest/CustomInitTest.java

If we add a new jetty filter holder to the filter chain through `applyCustomConfiguration` , it gets configured after the jersey servlet as the jersey servlet is configured first. Due to this the jetty filter is not triggered on incoming requests.
This PR swaps the order of configuring customConfiguration and jersey servlet, so that requests can be routed as expected.

changing order for filter configuration [CPSEC-482]

---

fips-tests/pom.xml

Rather than have our own versions of BC FIPS dependencies to keep up to date, we can rely on the versions pulled in from common. This will reduce the number of CVE updates we have to make in the future.

Update bcfips modules (#17)

---

core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/SslConfig.java

SslConfig.DEFAULT_CONFIG will log unrelated RestConfig values, which will confuse the application log, so disable it.

Don't log RestConfig value when creating DEFAULT_SSL config

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/handlers/ExpectedSniHandler.java
core/src/main/java/io/confluent/rest/handlers/SniHandler.java
core/src/main/java/io/confluent/rest/handlers/SniUtils.java

Add support for a list of expected SNI headers, configured using `expected.sni.headers`. If this is present, and the SNI check is not enabled, it logs a warning when an unexpected SNI header is present on a connection. This can be used prior to enabling the SNI check to validate that the check will not be disruptive.

Log unexpected SNI headers in REST

---

core/pom.xml
pom.xml

Folks, 
The update of jersey-bean in :
https://github.com/confluentinc/rest-utils/commit/903dcf49f770092cc011b10d57c5a7486ad2786c 
did not account for an update of the transitive dependency that no longer needs to be excluded  / redefined. 
This addresses a bizzare zombie CVE-2023-1932:
https://nvd.nist.gov/vuln/detail/CVE-2023-1932
Note:
NVD Published Date:
11/07/2024 
CVE number from 2023.

remove the hibernate-validator exclusion no longer needed due to updated version of jersey-bean

---

core/pom.xml
pom.xml

This removes hardcoded hibernate validator version, so it will pick up from the fix version `6.2.0.Final` for resolving CVE-2023-1932.
```
mvn dependency:tree | grep hibernate-validator
[INFO] |  +- org.hibernate.validator:hibernate-validator:jar:6.2.0.Final:compile
[INFO] |  |  +- org.hibernate.validator:hibernate-validator:jar:6.2.0.Final:compile
[INFO] |  |  +- org.hibernate.validator:hibernate-validator:jar:6.2.0.Final:compile
[INFO] |  |  +- org.hibernate.validator:hibernate-validator:jar:6.2.0.Final:compile
[INFO] |  |  +- org.hibernate.validator:hibernate-validator:jar:6.2.0.Final:compile
```

Remove hardcoded hibenate-validator version to fix CVE-2023-1932

---

core/src/main/java/io/confluent/rest/exceptions/KafkaExceptionMapper.java
core/src/test/java/io/confluent/rest/KafkaExceptionMapperTest.java

We don't handle UnknownTopicIdException gracefully, which leads to 500 error response, so this is to fix this.
The exception can happen if the user issuing topic deletion multiple times for the same topic.
Refs:
- https://confluentinc.atlassian.net/browse/KOP-192

Map UnknownTopicIdException to 404 code

---

checkstyle/suppressions.xml
core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/DoSFilter.java
core/src/main/java/io/confluent/rest/JettyDosFilterMultiListener.java
core/src/main/java/io/confluent/rest/jetty/DoSFilter.java
core/src/main/java/io/confluent/rest/metrics/Jetty429MetricsDosFilterListener.java
core/src/test/java/io/confluent/rest/JettyDosFilterMultiListenerIntegrationTest.java
core/src/test/java/io/confluent/rest/JettyDosFilterMultiListenerTest.java
core/src/test/java/io/confluent/rest/metrics/Jetty429MetricsDosFilterListenerTest.java

`jetty-servlets` package is currently pinned to 9.4.53 since there was a breaking change in the `DoSFilter`. We want to bump the servlets package to a higher version, so we can copy the DoSFilter from 9.4.53 as a short-term solution to allow the version bump w/o incurring the change in behavior.
There will be follow-up PR(s) to bump the jetty versions

KNET-14907: Add DoSFilter from Jetty 9.4.53

---

pom.xml

alternate update of async_http_client going from 2.2.0 to 2.12.4 (that was just recently published) 
alternative to updating to major version 3.0.1 see #517

[CC-30955]update async_http_client without upgrade of major version

---

pom.xml

Bump asynchttpclient to version 2.12.4 in 7.7.0-cp6

KNET-17108: Bump asynchttpclient to version 2.12.4 in 7.7.0-cp6 (#18)

---

core/src/main/java/io/confluent/rest/handlers/ExpectedSniHandler.java

Include the request URI in the log messages from `ExpectedSniHandler`

Include request URI in SNI logging

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java

We noticed that the percentile latency metrics in rest-utils (request-latency-95 and request-latency-99) are capped out at 10s (code [ref](https://github.com/confluentinc/rest-utils/blob/7.6.x/core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java#L325)). 
The PR makes PERCENTILE_MAX_LATENCY_IN_MS configurable in RestConfig, with 10s as the default value.
[Slack thread](https://confluent.slack.com/archives/C3226NBLJ/p1713808819756109)

[DGS-18780] Ensure p99 metrics are correctly published

---

core/src/main/java/io/confluent/rest/RestConfig.java

Addressing the review comment on the previous [PR](https://github.com/confluentinc/rest-utils/pull/519) to make PERCENTILE_MAX_LATENCY configurable.
Added a validator for the value to avoid non positive values.

Added validator for PERCENTILE_MAX_LATENCY

---

checkstyle/suppressions.xml
core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/JettyDosFilterMultiListener.java
core/src/main/java/io/confluent/rest/jetty/DoSFilter.java
core/src/main/java/io/confluent/rest/metrics/Jetty429MetricsDosFilterListener.java
core/src/test/java/io/confluent/rest/JettyDosFilterMultiListenerIntegrationTest.java
core/src/test/java/io/confluent/rest/JettyDosFilterMultiListenerTest.java
core/src/test/java/io/confluent/rest/metrics/Jetty429MetricsDosFilterListenerTest.java
pom.xml

cherrypicks the commit that added our version of jetty 9.53 's DosFilter
then it removes the pinned jetty-servlets version from 9.53. (it should go to 9.57 from common)

[7.8.x] Allow for upgrade to jetty and unpin jetty-servlets

---

checkstyle/suppressions.xml
core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/JettyDosFilterMultiListener.java
core/src/main/java/io/confluent/rest/jetty/DoSFilter.java
core/src/main/java/io/confluent/rest/metrics/Jetty429MetricsDosFilterListener.java
core/src/test/java/io/confluent/rest/JettyDosFilterMultiListenerIntegrationTest.java
core/src/test/java/io/confluent/rest/JettyDosFilterMultiListenerTest.java
core/src/test/java/io/confluent/rest/metrics/Jetty429MetricsDosFilterListenerTest.java
pom.xml

cherrypicks the commit that added our version of jetty 9.53 's DosFilter
then it removes the pinned jetty-servlets version from 9.53. (it should go to 9.57 from common)

[7.9.x] Allow for upgrade to jetty and unpin jetty-servlets 

---

pom.xml

https://github.com/confluentinc/rest-utils/pull/515 was merged to master
we can now unpin jetty-servlets version

[master] Allow for upgrade to jetty and unpin jetty-servlets 

---

core/pom.xml
core/src/main/java/io/confluent/rest/alpn/server/BouncyCastleServerALPNProcessor.java

Changes: These changes address the Bouncy Castle issue described [here](https://confluentinc.atlassian.net/wiki/spaces/OAAC/pages/3950773390/Bouncy+Castle+test+failure+analysis).
Reason for Change: The changes fix an ALPN Processor error that occurs when Bouncy Castle jars are used with HTTP/2. The fix was originally implemented https://github.com/confluentinc/rest-utils/pull/477 and is now being backported to the 7.7.0-cp7 branch in this PR.

Backport http2 support changes to 7.7.0-cp7

---

checkstyle/suppressions.xml
core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/JettyDosFilterMultiListener.java
core/src/main/java/io/confluent/rest/jetty/DoSFilter.java
core/src/main/java/io/confluent/rest/metrics/Jetty429MetricsDosFilterListener.java
core/src/test/java/io/confluent/rest/JettyDosFilterMultiListenerIntegrationTest.java
core/src/test/java/io/confluent/rest/JettyDosFilterMultiListenerTest.java
core/src/test/java/io/confluent/rest/metrics/Jetty429MetricsDosFilterListenerTest.java
pom.xml

cherrypicks the commit that added our version of jetty 9.53 's DosFilter
then it removes the pinned jetty-servlets version from 9.53. (it should go to 9.57 from common)

[7.9.0] Allow for upgrade to jetty and unpin jetty-servlets

---

core/src/main/java/io/confluent/rest/ApplicationServer.java
core/src/test/java/io/confluent/rest/UnnamedApplicationIntegrationTest.java

One of the downstream projects uses a single application with null listener name (unnamed app), this allows them to configure the app with multiple unnamed listeners, for example `listeners="http://...:8080,https://...:443"` because the check for equality pass 
```
Objects.equals(connector.getName(), appListenerName)
```
However, [when they changed](https://github.com/confluentinc/cc-security-decisions/pull/1402/files) to use named listeners,`listeners="unsecured://...:8080,secure://...:443"`, this doesn't work any more because the application is unnamed why the listeners have name.
This change relaxes the rule for unnamed app.
**Note that:** using unnamed app needs to be aware that the configured NetworkTrafficListener are combined on all listeners, for example, if it is …

Allow attaching NetworkTrafficListener to connectors of unnamed application

---

pom.xml

https://github.com/confluentinc/common/commit/60322b8531dd93a1afc765080a43c3cb13392223 updated common repo to Jetty 12, our changes for rest-utils for Jetty 12 are not yet finished. Until they are, we will pin Jetty version to jetty 9 so that builds can succeed
our pom does not specify all of the jetty modules, so we need to override the ones we use. I scanned for them with
```
mvn dependency:tree | grep jetty | grep 12.0
```
and then added all of them w/ the overridden version to the pom in rest-utils-parent

Override jetty version to 9.4.57.v20241219

---

core/src/test/resources/log4j2.yaml
examples/src/main/resources/log4j2.yaml
fips-tests/src/test/resources/log4j2.yaml

Use `%p` for including log level in log output.

Fix log4j2 pattern config

---

pom.xml

Pin JDK to 17 since common will use 11 (since some clients rely on common)

Pin JDK to 17

---

licenses/NOTICE.confluent-common.txt
licenses/NOTICE.zookeeper.txt

Removing ZK related files and references since 8.0.x will not be shipped with it

Remove zk notice for cp 8.0.x release

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/handlers/PrefixSniHandler.java
core/src/main/java/io/confluent/rest/handlers/SniHandler.java
core/src/test/java/io/confluent/rest/PrefixSniHandlerIntegrationTest.java

In PrefixSniHandler, restrict sni prefix validation when sniServerName starts with `lsrc-`, otherwise fallback to the original SniHandler logic

Restrict sni prefix validation to certain prefix

---

core/src/test/java/io/confluent/rest/SpireTest.java

After pint-merging from 7.9.x, we noticed some build issue in the pipeline
https://semaphore.ci.confluent.io/jobs/fa93621f-a1f2-4275-b025-332b6cf960c7.
It seemed 7.9.x are still using javax while the mater branch is using jakarta instead.
We have to fix the dependency naming.

Fix jakarta usage in SpireTest.java

---

core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/exceptions/GenericExceptionMapper.java
core/src/test/java/io/confluent/rest/KafkaExceptionMapperTest.java

DELETE ACL call is returning 500, the root cause of it is something to do with how jetty is returning the response and having an error in that. We have not figured it out, however the customer is facing severe degradation because of it.
We see that the 500 error is being mapped by the `GenericExceptionMapper`. Based on the conversation in the incident - https://confluent.slack.com/archives/C092AD71BQQ/p1751624023427379?thread_ts=1751556210.161449&cid=C092AD71BQQ the plan is to instead return 429 specifically for this error so that the customer retries the call instead of just exiting.
We also see [this](https://github.com/confluentinc/rest-utils/blob/146b606db52117e4568955a3c5f7f6ba4fe2d655/core/src/main/java/io/confluent/rest/exceptions/GenericExceptionMapper.java#L38) log which suggests …

temp: for inc-3209, we return a 429 instead of 500

---

core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java
fips-tests/src/test/java/io/confluent/rest/Http2FipsTest.java

Master build is failing with these flaky tests. How is it deemed flaky? Because a different run fails a different tests.
Only FIPS tests failing in this run - https://semaphore.ci.confluent.io/workflows/32a65340-2ab1-457d-860c-06fa977de64e/summary?report_id=17990af8-cb17-371c-9a8e-215e0e201902
Only testException5xxMetrics failing in this run - https://semaphore.ci.confluent.io/workflows/26154b0f-9ecc-4197-935d-43b88fbf00b5/summary?report_id=17990af8-cb17-371c-9a8e-215e0e201902
Only testGlobalLatencyMetricsForErrorsBeforeResourceMatching failing in this run https://semaphore.ci.confluent.io/workflows/50a06e36-6869-4ae8-b7ea-a1894f4dc327/summary?report_id=17990af8-cb17-371c-9a8e-215e0e201902&test_id=a6f46777-fc43-3cbf-a436-f5751b16e2b6
JIRA to enable/delete these tests - …

disable: flaky tests with JIRA to fix in KNET-19715

---

core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java

We saw this stack trace while getting a 500 error.
There is an attempt to getProperty from the request after the RequestEvent has been finished. Since Jetty12 is quite aggressive in recycling the request and reponse, we run into an NPE, eventually causing the 500 intermittently. This is a defensive code to ensure we don't throw NPE and get the request tags at a much earlier stage to avoid this NPE.
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.server.Request.getAttribute(String)" because the return value of "org.eclipse.jetty.ee10.servlet.ServletApiRequest.getRequest()" is null
at org.eclipse.jetty.ee10.servlet.ServletApiRequest.getAttribute(ServletApiRequest.java:834)
at org.glassfish.jersey.servlet.ServletPropertiesDelegate.getProperty(ServletPropertiesDelegate.jav …
```

fix: Check for NPEs before accessing request or response related objects

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/TenantDosFilter.java
core/src/main/java/io/confluent/rest/TenantUtils.java
core/src/main/java/io/confluent/rest/jetty/DoSFilter.java
core/src/test/java/io/confluent/rest/JettyDosFilterMultiListenerIntegrationTest.java
core/src/test/java/io/confluent/rest/TenantUtilsTest.java

Please first read through the JIRA (and associated docs) [here](https://confluentinc.atlassian.net/browse/KNET-10736) to see motivation for this change. 
This implementation the suggestion in the JIRA to add tenant rate limiting by creating a new DoS Filter that overrides `extractUserId` with the tenant ID. Note that for both the V3 and V4 network, I was able to get the tenant ID from the path and extracting it from the hostname was not required for V4. But I've left the logic for hostname extraction as a fallback so V4 extraction will still work even if the path somehow doesn't have it.
Some implementation details:
- The order of the rate limiters currently goes from most most granular to least granular as I believe this makes the most sense: IP-based -> tenant-based -> global. Ideally …

KNET-10736: Add tenant rate limiting to alleviate noisy neighbor problem

---

core/src/test/java/io/confluent/rest/RequestLogHandlerIntegrationTest.java
core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java
fips-tests/src/test/java/io/confluent/rest/Http2FipsTest.java

My previous PR(#581) only merged to `master` , so `8.0.x` and `8.1.x` are out of sync. Also, some flaky tests are disabled base on #599

[Chore] Sync master to old branches

---

core/src/main/java/io/confluent/rest/Application.java
core/src/main/java/io/confluent/rest/RestConfig.java
core/src/main/java/io/confluent/rest/TenantDryRunFilter.java
core/src/main/java/io/confluent/rest/TenantUtils.java

This builds on the previous PR (#593) to add a dry-run mode for tenant rate limiting. I'm creating a separate PR for this as this is temporary code just to be used for the initial testing (as mentioned [here](https://confluentinc.atlassian.net/wiki/spaces/~712020196c4f65f87449a1834c0930c2dc26fe/pages/4636246473/Noisy+Neighbor+Problem+in+Multi-Tenant+Clusters#Deployment-%2F-Rollout-Considerations)) and I don't want to obscure the logic of the main PR. 
When in dry-run mode, we don't do any actual tenant rate limiting, but simply observe the results of tenant extraction. This is important to verify in production so we can catch any potential edge cases that result in failed tenant extraction.

KNET-19517: Add dry-run mode for tenant rate limiting

---

core/pom.xml

We realized that `rest-util`  can't be deployed properly to linux server with spire enabled because the redundant dependency introduced. Please see this [thread](https://confluent.slack.com/archives/C0257BGCH0E/p1756142986631539). Akshay already tested this new change in this cluster and it worked.

[spire] remove explicit grpc-netty-linux

---

core/src/main/java/io/confluent/rest/TenantUtils.java
core/src/test/java/io/confluent/rest/TenantUtilsTest.java

Currently, tenant rate limiting prioritizes extracting the LKC ID from the request path. This is not always reliable as `DosFilter`s occur before auth, which means even bad requests that eventually get rejected will still create a rate limiter for this tenant. In the extreme case, a malicious client could use another tenant's LKC in order to throttle them
The fix here has two parts (the first is this PR, the second is an LD flag change)
1. Reverse the order of extraction methods. Before, we first attempted path extraction (as this works for both V3 and V4) and then fallback to the more reliable hostname extraction (V4 only). By first attempting hostname extraction, that means V4 networks will never extract the LKC from the path, eliminating the risk above (see below for why hostname …

Tenant rate limiting reliability improvement for V4 networking 

---

core/pom.xml
pom.xml

This is required as a part of a CVE fix. We need the exclusions in order to avoid the `grpc-netty-macos-aarch64` dependency which doesn't work with linux based systems.
In case we were to use `0.8.11` for `java-spiffe-provider`, we would be able to do everything on linux. This is because [0.8.11](https://mvnrepository.com/artifact/io.spiffe/java-spiffe-provider/0.8.11) uses [grpc-netty-linux](https://mvnrepository.com/artifact/io.spiffe/grpc-netty-linux) as a runtime dependency.
However, if we are to use [0.8.13](https://mvnrepository.com/artifact/io.spiffe/java-spiffe-provider/0.8.13) (latest), it uses [grpc-netty-macos-aarch64](https://mvnrepository.com/artifact/io.spiffe/grpc-netty-macos-aarch64) as a runtime dependency, and hence we face the following error in linux:
```shell …
```

Update java-spiffe version to 0.8.13

---

core/src/main/java/io/confluent/rest/handlers/SniUtils.java

Make getSniServerName public to be used in downstream applications. Port of https://github.com/confluentinc/rest-utils/pull/610

DGS-22074 Make getSniServerName public
