confluentinc/rest-utils

- core/src/main/java/io/confluent/rest/exceptions/ConstraintViolationExceptionMapper.java
- core/src/test/java/io/confluent/rest/ExceptionHandlingTest.java
> pass down exception message if we are missing any explicit constraint violations

- core/src/main/java/io/confluent/rest/Application.java
- core/src/main/java/io/confluent/rest/RestConfig.java
> allowed->allow

- README.md
- core/pom.xml
- core/src/main/java/io/confluent/rest/Application.java
- core/src/main/java/io/confluent/rest/RestConfig.java
- core/src/test/java/io/confluent/rest/ApplicationTest.java
- core/src/test/java/io/confluent/rest/SslTest.java
- core/src/test/java/io/confluent/rest/TestMetricsReporter.java
- core/src/test/resources/log4j.properties
- pom.xml
This is a copy of https://github.com/confluentinc/rest-utils/pull/38 with two changes: all commits rebased into one; made against the `3.x` branch instead of `master`.
> https support.

- core/src/main/java/io/confluent/rest/Application.java
- core/src/test/java/io/confluent/rest/StaticResourcesTest.java
- core/src/test/resources/static/index.html
- examples/src/main/java/io/confluent/rest/examples/helloworld/HelloWorldApplication.java
- examples/src/main/resources/static/index.html
> add support for static resources

- core/src/main/java/io/confluent/rest/Application.java
> we need more filters

- pom.xml
> bumping dependencies

- core/pom.xml
- pom.xml
- test/pom.xml
dependent on: https://github.com/confluentinc/common/pull/43
> Pom madness

- core/pom.xml
- examples/pom.xml
- package/pom.xml
- pom.xml
- test/pom.xml
highly relevant: https://github.com/confluentinc/common/pull/49
> moving deps up up up

- core/src/main/java/io/confluent/rest/Application.java
> Check for URI scheme before checking URI port

- core/src/main/java/io/confluent/rest/Application.java
- core/src/main/java/io/confluent/rest/RestConfig.java
Related PR https://github.com/confluentinc/common/pull/75
> Keystore and trustore password mapped to password type

- core/src/main/java/io/confluent/rest/Application.java
- core/src/main/java/io/confluent/rest/RestConfig.java
Dependent PR : https://github.com/confluentinc/common/pull/88
> Ability to configure metrics tags

- core/src/main/java/io/confluent/rest/Application.java
Opening PR because I don't see an easy want to enable `Slf4jRequestLog.setExtended()` right now and there may be a use case for extended logging in the near future; however, there may also be more utility to allowing the request log to be pluggable in other circumstances as well.
> Make server request log pluggable.

- pom.xml
> Update jackson and jetty

- core/src/main/java/io/confluent/rest/Application.java
- core/src/test/java/io/confluent/rest/GzipHandlerIntegrationTest.java
- core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java
* restore proper error dispatch test removed in #71 
* switch from deprecated GzipFilter to GzipHandler
* add integration test for gzip encoding
> Jetty 9.4 follow-up

- pom.xml
depends on https://github.com/confluentinc/common/pull/161
> use bouncycastle version from common pom

- core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
- core/src/test/java/io/confluent/rest/metrics/RequestScopedMetricsIntegrationTest.java
- core/src/test/java/io/confluent/rest/metrics/RuntimeMetricsIntegrationTest.java
Signed-off-by: Arjun Satish <arjun@confluent.io>
> CC-2533: Add support for runtime tags in metrics

- core/src/test/java/io/confluent/rest/SslTest.java
- pom.xml
Java 11 + TLS 1.3 here we come
> upgrade to jetty 9.4.12

- core/src/main/java/io/confluent/rest/Application.java
- core/src/main/java/io/confluent/rest/RestConfig.java
- core/src/main/java/io/confluent/rest/extension/ResourceExtension.java
- core/src/test/java/io/confluent/rest/ApplicationTest.java
I added this. It's not released and its only used by KSQL so far. I'll update KSQL.
> Fix typo in package name.

- core/src/main/java/io/confluent/rest/exceptions/KafkaExceptionMapper.java
- core/src/test/java/io/confluent/rest/KafkaExceptionMapperTest.java
- Add a common Kafka Exception Mapper which can be be used all rest-projects
> Add KafkaExceptionMapper

- pom.xml
- 9.4.14.v20181114 -> 9.4.18.v20190429
> SEC-191 - Upgrade Jetty in rest-utils

- package/src/assembly/package.xml
Make changes on old branch and merge with pint.
> use maven to generate archive

- core/src/main/java/io/confluent/rest/Application.java
- core/src/main/java/io/confluent/rest/ApplicationGroup.java
- core/src/main/java/io/confluent/rest/ApplicationServer.java
- core/src/test/java/io/confluent/rest/ApplicationGroupTest.java
- core/src/test/java/io/confluent/rest/ApplicationTest.java
- core/src/test/java/io/confluent/rest/IdleTimeoutConfigTest.java
- core/src/test/java/io/confluent/rest/SslTest.java
- core/src/test/java/io/confluent/rest/TestRestConfig.java
Cherry-Pick of #155 from master to 5.4.x.
> Enable support for multiple servlets on a single Jetty Server (#155)

- core/src/main/java/io/confluent/rest/ApplicationServer.java
- core/src/main/java/io/confluent/rest/RestConfig.java
- core/src/test/java/io/confluent/rest/SslTest.java
> Revert "CPKAFKA-4948: Make ssl.client.auth for REST consistent with Kafka (#175)"

- core/src/main/java/io/confluent/rest/exceptions/DebuggableExceptionMapper.java
- core/src/main/java/io/confluent/rest/exceptions/GenericExceptionMapper.java
- core/src/main/java/io/confluent/rest/exceptions/WebApplicationExceptionMapper.java
- core/src/test/java/io/confluent/rest/WebApplicationExceptionMapperTest.java
Jira ticket https://confluentinc.atlassian.net/browse/DG-1183
> DG:1183 Address http status 422 which is not supported in Response.status in  rest-util's ExceptionMapper

- pom.xml
To keep Jetty consistent: https://github.com/apache/kafka/pull/10526/files
> Upgrade Jetty to 9.4.39.v20210325

- pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2021-28168
> fix: CVE-2021-28168

- pom.xml
https://confluentinc.atlassian.net/browse/DGS-1621
> DGS-1621 Upgrade Jetty to 9.4.40

- core/src/main/java/io/confluent/rest/ApplicationServer.java
- core/src/test/java/io/confluent/rest/Http2Test.java
Fixing a couple of minor build problems that slipped through.
> Fix build problems

- core/src/main/java/io/confluent/rest/validation/ConstraintViolations.java
- examples/src/main/java/io/confluent/rest/examples/helloworld/HelloWorldApplication.java
- examples/src/main/java/io/confluent/rest/examples/helloworld/HelloWorldResource.java
- examples/src/main/java/io/confluent/rest/examples/helloworld/HelloWorldRestConfig.java
- test/src/main/java/io/confluent/rest/EmbeddedServerTestHarness.java
- test/src/main/java/io/confluent/rest/Generics.java
> fix additional checkstyle issues

- pom.xml
> Upgrade Jetty to  9.4.43.v20210629

- core/src/test/java/io/confluent/rest/SslTest.java
Jira ticket: https://confluentinc.atlassian.net/browse/MMA-11014
> MMA-11014: wrap SSLException

- pom.xml
This is to upgrade Netty to 4.1.68.Final.
> Upgrade Netty Version

- pom.xml
This PR updates `jetty-server` to `9.4.44.v20210927`.
```
➜  rest-utils git:(update-jetty-server-5-3-x) mvn dependency:tree -Dincludes=org.eclipse.jetty:jetty-server
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.15
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 15
[INFO] os.detected.classifier: osx-x86_64
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] rest-utils-parent …
```
> APIF-2027: Upgrade jetty-server to 9.4.44.v20210927.

- .github/CODEOWNERS
Email from Mayuri Shinkar
By 02/01/2022 - Please ensure that your repo has a CODEOWNERS file defined and present in your repository Note: (If your repo does not have a CODEOWNERS file you need to create one by 02/01/2022 else you won’t be able to commit to your repo after this change)
> KREST-3636 all repos need a codeowners file

- core/pom.xml
- examples/pom.xml
Automatic merge failed:
```
Checking for unmerged commits
from 7.2.x to master
151d97f34 Switch from confluent-log4j to reload4j  (#311)
Do you want to merge the commits to all downstream branches? [y/N]: y
Merging 7.2.x into master
Pushing master
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Waiting on code owner review from confluentinc/kafka-rest-eng.
To github.com:confluentinc/rest-utils
! [remote rejected]     master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:confluentinc/rest-utils'
Command "git push origin master" returned non-zero exit status 1
Could not merge automatically -- see above for details, so you gotta do it yourself manually.
```
The underlying PR is #311.
> APIF-2427: Merge 7.2.x to master

- core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
Minor cosmetic refactoring, to be followed by bug fixes and new changes in this class
> MINOR: Refactor MetricsResourceMethodApplicationListener

- core/pom.xml
- examples/pom.xml
Cherry-pick of https://github.com/confluentinc/rest-utils/commit/151d97f34ed2467446e7e0b1c640fb6e8fec7e0a.
> APIF-2714: Switch from confluent-log4j to reload4j  (5.4.x)

- core/src/main/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListener.java
- core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java
Similar to https://github.com/confluentinc/rest-utils/pull/345, add cumulative counters for errors.
> MINOR: Add error cumulative counters in MetricsResourceMethodApplicationListener

- core/src/main/java/io/confluent/rest/Application.java
- core/src/main/java/io/confluent/rest/exceptions/JsonMappingExceptionMapper.java
- core/src/main/java/io/confluent/rest/exceptions/JsonParseExceptionMapper.java
- core/src/test/java/io/confluent/rest/JsonMappingExceptionMapperTest.java
- core/src/test/java/io/confluent/rest/JsonParseExceptionMapperTest.java
https://github.com/confluentinc/rest-utils/pull/349 should be pint merged to all the branches from 5.4.x to 7.3.x, but pint merge can only merge from old branches to new ones, so I cherry-picked the changes to 5.4.x
> Cherry-pick https://github.com/confluentinc/rest-utils/pull/349 to 5.4.x

- core/pom.xml
- examples/pom.xml
- package/pom.xml
- pom.xml
- test/pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
> Merge Conflict Resolution (from 7.1.x to 7.2.x)

- core/src/main/java/io/confluent/rest/ApplicationServer.java
- core/src/main/java/io/confluent/rest/RestConfig.java
- core/src/main/java/io/confluent/rest/errorhandlers/NoJettyDefaultStackTraceErrorHandler.java
- core/src/test/java/io/confluent/rest/CsrfHandlingTest.java
- core/src/test/java/io/confluent/rest/ErrorHandlerIntegrationTest.java
This cherry pick commit da5de82d07f3ae858ec526f1ada07ee470e039bb of PR https://github.com/confluentinc/rest-utils/pull/379 for option to suppress stack trace in response.
> Backport KREST-8335 to branch 7.2.x

- core/src/main/java/io/confluent/rest/ApplicationServer.java
- core/src/main/java/io/confluent/rest/RestConfig.java
- core/src/main/java/io/confluent/rest/errorhandlers/NoJettyDefaultStackTraceErrorHandler.java
- core/src/test/java/io/confluent/rest/CsrfHandlingTest.java
- core/src/test/java/io/confluent/rest/ErrorHandlerIntegrationTest.java
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
> Merge Conflict Resolution (from 7.2.x to 7.3.x)

- core/pom.xml
- examples/pom.xml
- package/pom.xml
- pom.xml
- test/pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
> Merge Conflict Resolution (from 7.3.x to 7.4.x)

- core/pom.xml
- core/src/main/java/io/confluent/rest/Application.java
- core/src/test/java/io/confluent/rest/ErrorHandlerIntegrationTest.java
- core/src/test/java/io/confluent/rest/RequestLogHandlerIntegrationTest.java
- core/src/test/java/io/confluent/rest/TestUtils.java
- pom.xml
Backport commit 37b9c48db285c3c0954724ce08a3a9f5546a158a for duplicate request log fix to 7.2.x (customer request)
> Cherry pick KREST-1553 for duplicate log fix

- core/src/main/java/io/confluent/rest/ApplicationServer.java
- core/src/main/java/io/confluent/rest/RestConfig.java
Very simple PR, just to improve doc quality
> Fix typo in doc and make private property final

- core/src/main/java/io/confluent/rest/FileWatcher.java
- core/src/main/java/io/confluent/rest/SslFactory.java
- core/src/test/java/io/confluent/rest/SslCertReloadTest.java
- core/src/test/java/io/confluent/rest/SslTest.java
Flaky test for SSL cert auto reload seems to be failing because the code itself isn't rock-solid :)
> KREST-11276 - Tighten SSL auto cert reload

- Jenkinsfile
- service.yml
You will need to run service-bot and merge the PR it creates. [See the instructions](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#How-do-I-apply-changes-from-service.yml?)  
If applicable, [apply these changes to release branches](https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#I-only-see-changes-for-master.-How-do-I-apply-to-release-branches%3F)
This PR is the first step in migrating this repo from Jenkins to Semaphore.  
Once you see things are running smoothly on Semaphore for this repo, open a follow-up PR to delete the Jenkinsfile.  
This PR does two things:
1) Disables jenkins deploy.
2) Sets up cc-service-bot to create a semaphore.yaml. -> Expect a PR …
> Migration: Jenkins -> Semaphore

- Jenkinsfile
> Disable Jenkins deploy

- core/src/main/java/io/confluent/rest/ApplicationServer.java
- core/src/test/java/io/confluent/rest/MetricsListenerIntegrationTest.java
- core/src/test/java/io/confluent/rest/RateLimitNetworkTrafficListenerTest.java
- core/src/test/java/io/confluent/rest/RequestLogHandlerIntegrationTest.java
Register MetricsListener correctly to the connector for the designated listener.
> KREST-11856 Correctly registry listener to the application's NetworkTrafficServerConnector connector

- core/src/test/java/io/confluent/rest/RequestLogHandlerIntegrationTest.java
- core/src/test/java/io/confluent/rest/SslTest.java
As title said, this attempt to resolve failed build of master for both Jenkins and Semaphore.
> KNET-13691 resolve tests that are failing on Jenkins and Semaphore

- core/src/main/java/io/confluent/rest/RestConfig.java
- core/src/test/java/io/confluent/rest/RestConfigTest.java
Follow up https://github.com/confluentinc/rest-utils/pull/464, this is to improve the usability of doLog for downstream projects.
> KNET-14372 Getter for doLog and add helper config method

- core/src/test/java/io/confluent/rest/metrics/MetricsResourceMethodApplicationListenerIntegrationTest.java
https://confluent.slack.com/archives/C06CFQNK2BF/p1717190549947749?thread_ts=1717169007.420509&cid=C06CFQNK2BF
> Disabling flakey test

- .github/CODEOWNERS
https://confluentinc.atlassian.net/browse/APIT-623?focusedCommentId=1694284
> Remove API team from CODEOWNERS

- examples/src/main/resources/log4j2.yaml
- licenses/NOTICE.confluent-common.txt
remove zk references as we won't support it after cp 8.0
> remove zk references
